/**
 * Cambric Labs — Concept Catalog
 *
 * Concepts are language-agnostic units of knowledge (e.g. "variable",
 * "for-loop", "ownership"). They form a directed acyclic graph via
 * prerequisite edges. The adaptive scheduler uses this graph to ensure a
 * learner never meets a concept before its prerequisites.
 *
 * Aliases are used by the semantic-duplicate detector so that, e.g.,
 * "function" and "method" and "procedure" can be recognized as related
 * across languages without false-positive duplicate flags.
 */
import type { Concept } from '../types'

export const CONCEPTS: Concept[] = [
  {
    id: 'program',
    title: 'Program',
    summary: 'A sequence of instructions a computer executes.',
    prerequisiteConceptIds: [],
    aliases: ['code', 'script'],
  },
  {
    id: 'statement',
    title: 'Statement',
    summary: 'A single instruction that performs an action.',
    prerequisiteConceptIds: ['program'],
    aliases: ['instruction'],
  },
  {
    id: 'instruction',
    title: 'Machine Instruction',
    summary: 'A single CPU operation encoded as bits the processor can directly execute.',
    prerequisiteConceptIds: ['binary', 'cpu'],
    aliases: ['machine code instruction'],
  },
  {
    id: 'expression',
    title: 'Expression',
    summary: 'A piece of code that evaluates to a value.',
    prerequisiteConceptIds: ['statement'],
    aliases: ['value-producing code'],
  },
  {
    id: 'variable',
    title: 'Variable',
    summary: 'A named container that stores a value.',
    prerequisiteConceptIds: ['statement'],
    aliases: ['binding', 'name'],
  },
  {
    id: 'assignment',
    title: 'Assignment',
    summary: 'Storing a value into a variable.',
    prerequisiteConceptIds: ['variable'],
    aliases: ['reassignment'],
  },
  {
    id: 'type',
    title: 'Type',
    summary: 'A classification of data that determines valid operations.',
    prerequisiteConceptIds: ['variable'],
    aliases: ['data type'],
  },
  {
    id: 'literal',
    title: 'Literal',
    summary: 'A fixed value written directly in source, e.g. 42 or "hi".',
    prerequisiteConceptIds: ['expression'],
    aliases: ['constant value'],
  },
  {
    id: 'operator',
    title: 'Operator',
    summary: 'A symbol performing an operation on one or more operands.',
    prerequisiteConceptIds: ['expression'],
    aliases: ['operation'],
  },
  {
    id: 'function',
    title: 'Function',
    summary: 'A reusable, named block of code that takes inputs and returns a result.',
    prerequisiteConceptIds: ['variable', 'statement'],
    aliases: ['method', 'procedure', 'subroutine'],
  },
  {
    id: 'parameter',
    title: 'Parameter',
    summary: 'A named input a function accepts.',
    prerequisiteConceptIds: ['function'],
    aliases: ['argument', 'formal parameter'],
  },
  {
    id: 'return-value',
    title: 'Return Value',
    summary: 'The value a function produces back to its caller.',
    prerequisiteConceptIds: ['function'],
    aliases: ['result'],
  },
  {
    id: 'control-flow',
    title: 'Control Flow',
    summary: 'The order in which statements execute.',
    prerequisiteConceptIds: ['statement'],
    aliases: ['flow of control'],
  },
  {
    id: 'conditional',
    title: 'Conditional',
    summary: 'Executing code only when a condition is true.',
    prerequisiteConceptIds: ['control-flow', 'expression'],
    aliases: ['if statement', 'branching'],
  },
  {
    id: 'boolean-logic',
    title: 'Boolean Logic',
    summary: 'Combining true/false values with and, or, not.',
    prerequisiteConceptIds: ['expression'],
    aliases: ['logical operators'],
  },
  {
    id: 'short-circuit',
    title: 'Short-Circuit Evaluation',
    summary: 'When and/or stop early once the result is determined.',
    prerequisiteConceptIds: ['boolean-logic'],
    aliases: ['lazy evaluation', 'short-circuiting'],
  },
  {
    id: 'truthiness',
    title: 'Truthiness',
    summary: 'How non-boolean values are coerced to true/false in conditions.',
    prerequisiteConceptIds: ['boolean-logic'],
    aliases: ['falsy', 'truthy'],
  },
  {
    id: 'loop',
    title: 'Loop',
    summary: 'Repeating a block of code while a condition holds.',
    prerequisiteConceptIds: ['control-flow'],
    aliases: ['iteration', 'repetition'],
  },
  {
    id: 'for-loop',
    title: 'For Loop',
    summary: 'A loop with an explicit counter over a range or sequence.',
    prerequisiteConceptIds: ['loop'],
    aliases: ['counting loop'],
  },
  {
    id: 'while-loop',
    title: 'While Loop',
    summary: 'A loop repeating while a condition remains true.',
    prerequisiteConceptIds: ['loop'],
    aliases: ['condition loop'],
  },
  {
    id: 'collection',
    title: 'Collection',
    summary: 'A data structure holding multiple values.',
    prerequisiteConceptIds: ['variable', 'type'],
    aliases: ['container'],
  },
  {
    id: 'array',
    title: 'Array',
    summary: 'An indexed, fixed-size sequence of values.',
    prerequisiteConceptIds: ['collection'],
    aliases: ['list', 'vector'],
  },
  {
    id: 'string',
    title: 'String',
    summary: 'A sequence of characters representing text.',
    prerequisiteConceptIds: ['type'],
    aliases: ['text'],
  },
  {
    id: 'scope',
    title: 'Scope',
    summary: 'The region of code where a name is visible.',
    prerequisiteConceptIds: ['variable', 'function'],
    aliases: ['visibility', 'namespace'],
  },
  {
    id: 'recursion',
    title: 'Recursion',
    summary: 'A function calling itself on a smaller subproblem.',
    prerequisiteConceptIds: ['function', 'conditional'],
    aliases: ['self-reference'],
  },
  {
    id: 'base-case',
    title: 'Base Case',
    summary: 'The stopping condition that prevents infinite recursion.',
    prerequisiteConceptIds: ['recursion', 'conditional'],
    aliases: ['terminating case'],
  },
  {
    id: 'mutation',
    title: 'Mutation',
    summary: 'Changing a value or data structure in place.',
    prerequisiteConceptIds: ['assignment'],
    aliases: ['in-place change'],
  },
  {
    id: 'immutability',
    title: 'Immutability',
    summary: 'A value that cannot change after creation.',
    prerequisiteConceptIds: ['mutation'],
    aliases: ['constant data'],
  },
  {
    id: 'object',
    title: 'Object',
    summary: 'A bundle of state (fields) and behavior (methods).',
    prerequisiteConceptIds: ['variable', 'function'],
    aliases: ['instance'],
  },
  {
    id: 'class',
    title: 'Class',
    summary: 'A blueprint defining the fields and methods of objects.',
    prerequisiteConceptIds: ['object', 'type'],
    aliases: ['blueprint'],
  },
  {
    id: 'encapsulation',
    title: 'Encapsulation',
    summary: 'Hiding internal state behind an interface.',
    prerequisiteConceptIds: ['object', 'scope'],
    aliases: ['information hiding'],
  },
  {
    id: 'inheritance',
    title: 'Inheritance',
    summary: 'A class deriving fields and methods from another class.',
    prerequisiteConceptIds: ['class'],
    aliases: ['subclassing'],
  },
  {
    id: 'polymorphism',
    title: 'Polymorphism',
    summary: 'Treating different types through a common interface.',
    prerequisiteConceptIds: ['inheritance'],
    aliases: ['dynamic dispatch'],
  },
  {
    id: 'error-handling',
    title: 'Error Handling',
    summary: 'Detecting and responding to failures gracefully.',
    prerequisiteConceptIds: ['control-flow'],
    aliases: ['exceptions', 'try-catch'],
  },
  {
    id: 'memory-model',
    title: 'Memory Model',
    summary: 'How the language allocates and frees memory.',
    prerequisiteConceptIds: ['variable', 'mutation'],
    aliases: ['allocation'],
  },
  {
    id: 'ownership',
    title: 'Ownership',
    summary: 'A discipline where each value has a single owning scope.',
    prerequisiteConceptIds: ['memory-model', 'scope'],
    aliases: ['borrowing', 'lifetimes'],
  },
  {
    id: 'module-system',
    title: 'Module System',
    summary: 'Splitting code into reusable, importable units.',
    prerequisiteConceptIds: ['function', 'scope'],
    aliases: ['packages', 'imports'],
  },
  {
    id: 'testing',
    title: 'Testing',
    summary: 'Verifying code behaves correctly via executable checks.',
    prerequisiteConceptIds: ['function'],
    aliases: ['unit tests'],
  },
  {
    id: 'algorithm',
    title: 'Algorithm',
    summary: 'A precise, finite procedure for solving a problem.',
    prerequisiteConceptIds: ['function', 'control-flow'],
    aliases: ['procedure'],
  },
  {
    id: 'complexity',
    title: 'Computational Complexity',
    summary: 'How runtime/space grow with input size.',
    prerequisiteConceptIds: ['algorithm'],
    aliases: ['big-o', 'time complexity'],
  },
  {
    id: 'data-structure',
    title: 'Data Structure',
    summary: 'An organized way to store and access data.',
    prerequisiteConceptIds: ['collection'],
    aliases: ['container structure'],
  },
  {
    id: 'pointer',
    title: 'Pointer',
    summary: 'A value holding the address of other data.',
    prerequisiteConceptIds: ['memory-model'],
    aliases: ['reference'],
  },
  {
    id: 'map',
    title: 'Map',
    summary: 'A collection of key-to-value associations.',
    prerequisiteConceptIds: ['collection', 'array'],
    aliases: ['dictionary', 'dict', 'hashmap', 'hashtable', 'record'],
  },
  {
    id: 'set',
    title: 'Set',
    summary: 'A collection of unique values with no defined order.',
    prerequisiteConceptIds: ['collection'],
    aliases: ['unique collection'],
  },
  {
    id: 'iteration',
    title: 'Iteration',
    summary: 'Visiting each element of a collection in turn.',
    prerequisiteConceptIds: ['loop', 'collection'],
    aliases: ['traversal', 'enumeration'],
  },
  {
    id: 'index',
    title: 'Index',
    summary: 'A position used to access an element of an ordered collection.',
    prerequisiteConceptIds: ['array'],
    aliases: ['offset', 'position'],
  },
  {
    id: 'string-method',
    title: 'String Method',
    summary: 'An operation that transforms or inspects text.',
    prerequisiteConceptIds: ['string', 'function'],
    aliases: ['text operation'],
  },

  // ── Computing foundations ──────────────────────────────────────────
  {
    id: 'binary',
    title: 'Binary',
    summary: 'Base-2 representation of numbers using 0 and 1.',
    prerequisiteConceptIds: ['type'],
    aliases: ['base-2', 'bits'],
  },
  {
    id: 'cpu',
    title: 'CPU',
    summary: 'The processor that executes instructions one at a time.',
    prerequisiteConceptIds: ['program'],
    aliases: ['processor', 'central processing unit'],
  },
  {
    id: 'stack-memory',
    title: 'Stack',
    summary: 'LIFO region for function frames and local variables.',
    prerequisiteConceptIds: ['memory-model', 'function'],
    aliases: ['call stack region'],
  },
  {
    id: 'heap-memory',
    title: 'Heap',
    summary: 'Dynamic memory region for long-lived or large allocations.',
    prerequisiteConceptIds: ['memory-model'],
    aliases: ['dynamic memory'],
  },
  {
    id: 'compilation',
    title: 'Compilation',
    summary: 'Translating source code into machine code ahead of running.',
    prerequisiteConceptIds: ['program', 'cpu'],
    aliases: ['compiler'],
  },
  {
    id: 'interpretation',
    title: 'Interpretation',
    summary: 'Executing source code directly without a separate compile step.',
    prerequisiteConceptIds: ['program'],
    aliases: ['interpreter'],
  },
  {
    id: 'process',
    title: 'Process',
    summary: 'A running program with its own memory space.',
    prerequisiteConceptIds: ['program', 'memory-model'],
    aliases: ['running program'],
  },
  {
    id: 'filesystem',
    title: 'File System',
    summary: 'How an OS organizes data into files and directories.',
    prerequisiteConceptIds: ['program'],
    aliases: ['files', 'directories'],
  },
  {
    id: 'command-line',
    title: 'Command Line',
    summary: 'Text interface for invoking programs and managing files.',
    prerequisiteConceptIds: ['filesystem', 'process'],
    aliases: ['terminal', 'shell', 'cli'],
  },

  // ── Data structures (advanced) ─────────────────────────────────────
  {
    id: 'linked-list',
    title: 'Linked List',
    summary: 'A chain of nodes each pointing to the next.',
    prerequisiteConceptIds: ['data-structure', 'pointer'],
    aliases: ['singly linked list'],
  },
  {
    id: 'stack-ds',
    title: 'Stack (Data Structure)',
    summary: 'LIFO collection: push and pop from one end.',
    prerequisiteConceptIds: ['data-structure', 'collection'],
    aliases: ['lifo'],
  },
  {
    id: 'queue-ds',
    title: 'Queue (Data Structure)',
    summary: 'FIFO collection: enqueue at back, dequeue from front.',
    prerequisiteConceptIds: ['data-structure', 'collection'],
    aliases: ['fifo'],
  },
  {
    id: 'tree',
    title: 'Tree',
    summary: 'A hierarchical structure of nodes with one parent each.',
    prerequisiteConceptIds: ['data-structure', 'linked-list'],
    aliases: ['hierarchy'],
  },
  {
    id: 'binary-tree',
    title: 'Binary Tree',
    summary: 'A tree where each node has at most two children.',
    prerequisiteConceptIds: ['tree'],
    aliases: ['binary tree'],
  },
  {
    id: 'bst',
    title: 'Binary Search Tree',
    summary: 'An ordered binary tree enabling O(log n) search.',
    prerequisiteConceptIds: ['binary-tree', 'searching'],
    aliases: ['bst', 'ordered tree'],
  },
  {
    id: 'heap',
    title: 'Heap',
    summary: 'A tree satisfying the heap property; supports fast min/max.',
    prerequisiteConceptIds: ['binary-tree'],
    aliases: ['priority queue backing'],
  },
  {
    id: 'graph',
    title: 'Graph',
    summary: 'Nodes connected by edges; models networks and relations.',
    prerequisiteConceptIds: ['data-structure', 'tree'],
    aliases: ['network structure'],
  },
  {
    id: 'hashing',
    title: 'Hashing',
    summary: 'Mapping data to fixed-size values for fast lookup.',
    prerequisiteConceptIds: ['map', 'function'],
    aliases: ['hash function'],
  },
  {
    id: 'tuple',
    title: 'Tuple',
    summary: 'An ordered, fixed-size, immutable collection.',
    prerequisiteConceptIds: ['collection', 'immutability'],
    aliases: ['fixed record'],
  },

  // ── Algorithms ─────────────────────────────────────────────────────
  {
    id: 'searching',
    title: 'Searching',
    summary: 'Finding a target element within a collection.',
    prerequisiteConceptIds: ['algorithm', 'iteration'],
    aliases: ['lookup', 'find'],
  },
  {
    id: 'sorting',
    title: 'Sorting',
    summary: 'Arranging elements into a defined order.',
    prerequisiteConceptIds: ['algorithm', 'iteration', 'operator'],
    aliases: ['sort'],
  },
  {
    id: 'binary-search',
    title: 'Binary Search',
    summary: 'O(log n) search on a sorted collection by halving.',
    prerequisiteConceptIds: ['searching', 'sorting'],
    aliases: ['bisection search'],
  },
  {
    id: 'divide-and-conquer',
    title: 'Divide and Conquer',
    summary: 'Split a problem, solve parts, combine results.',
    prerequisiteConceptIds: ['recursion', 'algorithm'],
    aliases: ['split-solve-combine'],
  },
  {
    id: 'greedy',
    title: 'Greedy Algorithm',
    summary: 'Make the locally optimal choice at each step.',
    prerequisiteConceptIds: ['algorithm'],
    aliases: ['greedy'],
  },
  {
    id: 'dynamic-programming',
    title: 'Dynamic Programming',
    summary: 'Solve subproblems once and reuse their results.',
    prerequisiteConceptIds: ['recursion', 'algorithm', 'complexity'],
    aliases: ['dp', 'memoization'],
  },
  {
    id: 'backtracking',
    title: 'Backtracking',
    summary: 'Explore choices and undo them when they lead to a dead end.',
    prerequisiteConceptIds: ['recursion', 'algorithm'],
    aliases: ['constraint search'],
  },
  {
    id: 'bfs',
    title: 'Breadth-First Search',
    summary: 'Visit graph nodes level by level using a queue.',
    prerequisiteConceptIds: ['graph', 'queue-ds'],
    aliases: ['breadth first', 'level order'],
  },
  {
    id: 'dfs',
    title: 'Depth-First Search',
    summary: 'Visit graph nodes as deep as possible before backtracking.',
    prerequisiteConceptIds: ['graph', 'stack-ds', 'recursion'],
    aliases: ['depth first'],
  },

  // ── Software engineering ───────────────────────────────────────────
  {
    id: 'version-control',
    title: 'Version Control',
    summary: 'Tracking and managing changes to source code over time.',
    prerequisiteConceptIds: ['filesystem', 'program'],
    aliases: ['git', 'vcs'],
  },
  {
    id: 'branching',
    title: 'Branching',
    summary: 'Divergent lines of development in version control.',
    prerequisiteConceptIds: ['version-control'],
    aliases: ['branch', 'fork'],
  },
  {
    id: 'code-review',
    title: 'Code Review',
    summary: 'Systematically examining code before it is merged.',
    prerequisiteConceptIds: ['version-control'],
    aliases: ['peer review'],
  },
  {
    id: 'unit-testing',
    title: 'Unit Testing',
    summary: 'Testing individual units of code in isolation.',
    prerequisiteConceptIds: ['testing', 'function'],
    aliases: ['unit test'],
  },
  {
    id: 'integration-testing',
    title: 'Integration Testing',
    summary: 'Testing how multiple units work together.',
    prerequisiteConceptIds: ['unit-testing'],
    aliases: ['integration test'],
  },
  {
    id: 'debugging',
    title: 'Debugging',
    summary: 'Finding and fixing the root cause of incorrect behavior.',
    prerequisiteConceptIds: ['testing', 'error-handling'],
    aliases: ['troubleshooting'],
  },
  {
    id: 'design-pattern',
    title: 'Design Pattern',
    summary: 'A reusable solution to a recurring design problem.',
    prerequisiteConceptIds: ['object-oriented-design'],
    aliases: ['pattern'],
  },
  {
    id: 'object-oriented-design',
    title: 'Object-Oriented Design',
    summary: 'Modeling a system as cooperating objects.',
    prerequisiteConceptIds: ['object', 'function'],
    aliases: ['ood'],
  },
  {
    id: 'ci-cd',
    title: 'CI/CD',
    summary: 'Automating build, test, and deploy on every change.',
    prerequisiteConceptIds: ['version-control', 'unit-testing'],
    aliases: ['continuous integration', 'continuous deployment'],
  },

  // ── Web development ────────────────────────────────────────────────
  {
    id: 'http',
    title: 'HTTP',
    summary: 'The request/response protocol of the web.',
    prerequisiteConceptIds: ['process'],
    aliases: ['hypertext transfer protocol'],
  },
  {
    id: 'dom',
    title: 'DOM',
    summary: 'The in-memory tree a browser builds from HTML.',
    prerequisiteConceptIds: ['tree', 'html'],
    aliases: ['document object model'],
  },
  {
    id: 'html',
    title: 'HTML',
    summary: 'Markup that describes the structure of a web page.',
    prerequisiteConceptIds: ['program'],
    aliases: ['markup'],
  },
  {
    id: 'css',
    title: 'CSS',
    summary: 'Rules that describe how HTML elements are presented.',
    prerequisiteConceptIds: ['html'],
    aliases: ['styles'],
  },
  {
    id: 'rest',
    title: 'REST',
    summary: 'An architectural style for web APIs over HTTP.',
    prerequisiteConceptIds: ['http'],
    aliases: ['restful api'],
  },
  {
    id: 'json',
    title: 'JSON',
    summary: 'A text format for exchanging structured data.',
    prerequisiteConceptIds: ['object', 'string'],
    aliases: ['javascript object notation'],
  },
  {
    id: 'event-driven',
    title: 'Event-Driven Programming',
    summary: 'Flow controlled by events (clicks, messages, timers).',
    prerequisiteConceptIds: ['function', 'dom'],
    aliases: ['event handling'],
  },
  {
    id: 'async',
    title: 'Asynchronous Programming',
    summary: 'Starting work and handling results later without blocking.',
    prerequisiteConceptIds: ['function', 'event-driven'],
    aliases: ['async-await', 'promises', 'futures'],
  },
  {
    id: 'frontend-architecture',
    title: 'Frontend Architecture',
    summary: 'Organizing browser code into components and state.',
    prerequisiteConceptIds: ['dom', 'event-driven'],
    aliases: ['spa architecture'],
  },

  // ── Backend ────────────────────────────────────────────────────────
  {
    id: 'server',
    title: 'Server',
    summary: 'A process that listens for and handles requests.',
    prerequisiteConceptIds: ['http', 'process'],
    aliases: ['backend server'],
  },
  {
    id: 'api',
    title: 'API',
    summary: 'A defined interface for programs to talk to each other.',
    prerequisiteConceptIds: ['function', 'http'],
    aliases: ['application programming interface'],
  },
  {
    id: 'middleware',
    title: 'Middleware',
    summary: 'Functions chained between a request and its handler.',
    prerequisiteConceptIds: ['server', 'function'],
    aliases: ['request pipeline'],
  },
  {
    id: 'authentication',
    title: 'Authentication',
    summary: 'Verifying who a user is.',
    prerequisiteConceptIds: ['api', 'server'],
    aliases: ['auth'],
  },
  {
    id: 'authorization',
    title: 'Authorization',
    summary: 'Deciding what an authenticated user may do.',
    prerequisiteConceptIds: ['authentication'],
    aliases: ['permissions', 'authz'],
  },
  {
    id: 'caching',
    title: 'Caching',
    summary: 'Storing results to avoid recomputing or refetching them.',
    prerequisiteConceptIds: ['map', 'function'],
    aliases: ['cache'],
  },
  {
    id: 'rate-limiting',
    title: 'Rate Limiting',
    summary: 'Throttling how often a client may call an endpoint.',
    prerequisiteConceptIds: ['api'],
    aliases: ['throttling'],
  },

  // ── Databases ──────────────────────────────────────────────────────
  {
    id: 'database',
    title: 'Database',
    summary: 'An organized store of persistent data.',
    prerequisiteConceptIds: ['filesystem', 'data-structure'],
    aliases: ['db'],
  },
  {
    id: 'sql',
    title: 'SQL',
    summary: 'Declarative language for querying relational databases.',
    prerequisiteConceptIds: ['database', 'map'],
    aliases: ['structured query language'],
  },
  {
    id: 'index-db',
    title: 'Database Index',
    summary: 'A structure that speeds up lookups on a column.',
    prerequisiteConceptIds: ['database', 'hashing', 'tree'],
    aliases: ['index'],
  },
  {
    id: 'transaction',
    title: 'Transaction',
    summary: 'A unit of work that succeeds entirely or not at all.',
    prerequisiteConceptIds: ['database'],
    aliases: ['acid transaction'],
  },
  {
    id: 'normalization',
    title: 'Normalization',
    summary: 'Reducing redundancy by structuring tables with integrity.',
    prerequisiteConceptIds: ['database', 'sql'],
    aliases: ['normal forms'],
  },
  {
    id: 'nosql',
    title: 'NoSQL',
    summary: 'Non-relational database models (document, key-value, graph).',
    prerequisiteConceptIds: ['database'],
    aliases: ['document store', 'key-value store'],
  },

  // ── Systems programming ────────────────────────────────────────────
  {
    id: 'manual-memory',
    title: 'Manual Memory Management',
    summary: 'The programmer explicitly allocates and frees memory.',
    prerequisiteConceptIds: ['pointer', 'heap-memory'],
    aliases: ['malloc/free', 'manual allocation'],
  },
  {
    id: 'borrowing',
    title: 'Borrowing',
    summary: 'Temporarily lending access to a value without transferring ownership.',
    prerequisiteConceptIds: ['ownership'],
    aliases: ['rust borrowing', 'borrow checker'],
  },
  {
    id: 'lifetime',
    title: 'Lifetime',
    summary: 'The region of code in which a reference is valid.',
    prerequisiteConceptIds: ['borrowing', 'scope'],
    aliases: ['lifetimes', 'rust lifetime'],
  },
  {
    id: 'concurrency',
    title: 'Concurrency',
    summary: 'Making progress on multiple tasks within overlapping time.',
    prerequisiteConceptIds: ['process', 'function'],
    aliases: ['concurrent programming'],
  },
  {
    id: 'thread',
    title: 'Thread',
    summary: 'A unit of execution sharing memory within a process.',
    prerequisiteConceptIds: ['concurrency', 'process'],
    aliases: ['lightweight process'],
  },
  {
    id: 'synchronization',
    title: 'Synchronization',
    summary: 'Coordinating threads so they access shared data safely.',
    prerequisiteConceptIds: ['thread', 'concurrency'],
    aliases: ['locking', 'mutex'],
  },
  {
    id: 'networking',
    title: 'Networking',
    summary: 'How computers exchange data across connections.',
    prerequisiteConceptIds: ['process', 'http'],
    aliases: ['network protocols'],
  },

  // ── AI / ML ────────────────────────────────────────────────────────
  {
    id: 'statistics',
    title: 'Statistics',
    summary: 'Summarizing and reasoning about data with numbers.',
    prerequisiteConceptIds: ['function', 'collection'],
    aliases: ['descriptive statistics'],
  },
  {
    id: 'linear-algebra',
    title: 'Linear Algebra',
    summary: 'Vectors and matrices as the language of ML models.',
    prerequisiteConceptIds: ['function', 'array'],
    aliases: ['matrices', 'vectors'],
  },
  {
    id: 'machine-learning',
    title: 'Machine Learning',
    summary: 'Systems that improve at a task from data rather than rules.',
    prerequisiteConceptIds: ['statistics', 'linear-algebra', 'function'],
    aliases: ['ml'],
  },
  {
    id: 'neural-network',
    title: 'Neural Network',
    summary: 'Layered functions with learned weights mapping inputs to outputs.',
    prerequisiteConceptIds: ['machine-learning', 'linear-algebra'],
    aliases: ['neural net', 'nn'],
  },
  {
    id: 'training',
    title: 'Training',
    summary: 'Adjusting model parameters to reduce error on data.',
    prerequisiteConceptIds: ['neural-network', 'function'],
    aliases: ['model fitting', 'gradient descent'],
  },
  {
    id: 'transformer',
    title: 'Transformer',
    summary: 'Attention-based architecture behind modern language models.',
    prerequisiteConceptIds: ['neural-network'],
    aliases: ['attention model'],
  },
  {
    id: 'embedding',
    title: 'Embedding',
    summary: 'Representing items as vectors in a learned space.',
    prerequisiteConceptIds: ['machine-learning', 'linear-algebra'],
    aliases: ['vector representation'],
  },
  {
    id: 'llm',
    title: 'Large Language Model',
    summary: 'A transformer model trained on text at massive scale.',
    prerequisiteConceptIds: ['transformer', 'training'],
    aliases: ['large language model', 'foundation model'],
  },

  // ── Advanced development ───────────────────────────────────────────
  {
    id: 'parser',
    title: 'Parser',
    summary: 'Turns a sequence of tokens into a structured tree (AST).',
    prerequisiteConceptIds: ['tree', 'compilation'],
    aliases: ['parsing'],
  },
  {
    id: 'ast',
    title: 'AST',
    summary: 'A tree representing the structure of source code.',
    prerequisiteConceptIds: ['tree', 'parser'],
    aliases: ['abstract syntax tree'],
  },
  {
    id: 'static-analysis',
    title: 'Static Analysis',
    summary: 'Examining code without running it to find issues.',
    prerequisiteConceptIds: ['ast', 'parser'],
    aliases: ['linting'],
  },
  {
    id: 'cryptography',
    title: 'Cryptography',
    summary: 'Techniques for secure communication and data integrity.',
    prerequisiteConceptIds: ['function', 'binary'],
    aliases: ['crypto'],
  },
  {
    id: 'profiling',
    title: 'Profiling',
    summary: 'Measuring where a program spends time and memory.',
    prerequisiteConceptIds: ['debugging', 'complexity'],
    aliases: ['performance profiling'],
  },
  {
    id: 'distributed-systems',
    title: 'Distributed Systems',
    summary: 'Multiple computers cooperating as one system.',
    prerequisiteConceptIds: ['networking', 'concurrency'],
    aliases: ['distributed computing'],
  },
  {
    id: 'closure',
    title: 'Closure',
    summary: 'A function that captures variables from its defining scope.',
    prerequisiteConceptIds: ['scope', 'function'],
    aliases: ['lexical closure'],
  },
  {
    id: 'generator',
    title: 'Generator',
    summary: 'A function that yields values lazily, one at a time.',
    prerequisiteConceptIds: ['function', 'iteration'],
    aliases: ['lazy sequence', 'yield'],
  },
  {
    id: 'decorator',
    title: 'Decorator',
    summary: 'A function that wraps another to extend its behavior.',
    prerequisiteConceptIds: ['function', 'closure'],
    aliases: ['higher-order wrapper'],
  },
  {
    id: 'generic-type',
    title: 'Generics',
    summary: 'Writing code that works for many types via type parameters.',
    prerequisiteConceptIds: ['type', 'function'],
    aliases: ['parametric polymorphism', 'templates'],
  },
  {
    id: 'smart-contract',
    title: 'Smart Contract',
    summary: 'Self-executing code on a blockchain.',
    prerequisiteConceptIds: ['program', 'cryptography'],
    aliases: ['contract'],
  },
  {
    id: 'game-loop',
    title: 'Game Loop',
    summary: 'The update-render cycle driving real-time games.',
    prerequisiteConceptIds: ['loop', 'function'],
    aliases: ['render loop'],
  },
  {
    id: 'node',
    title: 'Node',
    summary: 'A container holding a value plus links to other nodes.',
    prerequisiteConceptIds: ['pointer', 'data-structure'],
    aliases: ['list node'],
  },
  {
    id: 'text',
    title: 'Text',
    summary: 'A sequence of characters representing human-readable content.',
    prerequisiteConceptIds: ['string'],
    aliases: ['plain text'],
  },
  {
    id: 'markup',
    title: 'Markup',
    summary: 'Text annotated with tags that label the structure and meaning of content.',
    prerequisiteConceptIds: ['text', 'type'],
    aliases: ['markup language'],
  },
  {
    id: 'element',
    title: 'Element',
    summary: 'A single tagged unit of a markup document (opening tag, content, closing tag).',
    prerequisiteConceptIds: ['markup'],
    aliases: ['tag', 'html element'],
  },
  {
    id: 'attribute',
    title: 'Attribute',
    summary: 'A key-value pair on a markup element providing extra information.',
    prerequisiteConceptIds: ['element'],
    aliases: ['html attribute'],
  },
  {
    id: 'query',
    title: 'Query',
    summary: 'A request to retrieve or modify data from a data store.',
    prerequisiteConceptIds: ['data-structure'],
    aliases: ['database query'],
  },
  {
    id: 'table',
    title: 'Table',
    summary: 'A collection of rows and columns storing records in a relational database.',
    prerequisiteConceptIds: ['data-structure'],
    aliases: ['database table', 'relation'],
  },
  {
    id: 'relational-model',
    title: 'Relational Model',
    summary: 'Organizing data as related tables with keys connecting them.',
    prerequisiteConceptIds: ['table', 'foreign-key'],
    aliases: ['relational database model'],
  },
  {
    id: 'foreign-key',
    title: 'Foreign Key',
    summary: 'A column referencing the primary key of another table to express a relationship.',
    prerequisiteConceptIds: ['table'],
    aliases: ['fk'],
  },
  {
    id: 'commit',
    title: 'Commit',
    summary: 'A recorded snapshot of the project state at one point in time in version control.',
    prerequisiteConceptIds: ['version-control'],
    aliases: ['git commit', 'revision'],
  },
  {
    id: 'branch',
    title: 'Branch',
    summary: 'A movable label pointing at a commit, enabling isolated lines of work.',
    prerequisiteConceptIds: ['commit', 'version-control'],
    aliases: ['git branch'],
  },
  {
    id: 'working-directory',
    title: 'Working Directory',
    summary: 'The files on disk that you edit, separate from staged and committed state.',
    prerequisiteConceptIds: ['version-control'],
    aliases: ['working tree'],
  },
  {
    id: 'model',
    title: 'Model',
    summary: 'A learned function that maps inputs to predicted outputs in machine learning.',
    prerequisiteConceptIds: ['machine-learning', 'function'],
    aliases: ['ml model', 'trained model'],
  },
  {
    id: 'feature',
    title: 'Feature',
    summary: 'A measurable property of data used as input to a machine learning model.',
    prerequisiteConceptIds: ['machine-learning'],
    aliases: ['input feature'],
  },
  {
    id: 'supervised-learning',
    title: 'Supervised Learning',
    summary: 'Training a model on labeled examples to predict outputs for new inputs.',
    prerequisiteConceptIds: ['machine-learning', 'training'],
    aliases: ['supervised machine learning'],
  },

  // ── Computer fundamentals (expanded) ────────────────────────────────
  {
    id: 'ram',
    title: 'RAM',
    summary: 'Volatile working memory the CPU reads and writes during execution.',
    prerequisiteConceptIds: ['cpu'],
    aliases: ['main memory', 'random access memory'],
  },
  {
    id: 'storage',
    title: 'Storage',
    summary: 'Non-volatile media (disk, SSD) that retains data without power.',
    prerequisiteConceptIds: ['filesystem'],
    aliases: ['disk', 'persistent storage'],
  },
  {
    id: 'hexadecimal',
    title: 'Hexadecimal',
    summary: 'Base-16 notation compactly representing bytes and addresses.',
    prerequisiteConceptIds: ['binary'],
    aliases: ['hex', 'base 16'],
  },
  {
    id: 'operating-system',
    title: 'Operating System',
    summary: 'Software managing hardware resources and running programs.',
    prerequisiteConceptIds: ['process', 'filesystem'],
    aliases: ['os'],
  },
  {
    id: 'terminal',
    title: 'Terminal',
    summary: 'Text interface sending commands to and receiving output from a shell.',
    prerequisiteConceptIds: ['command-line'],
    aliases: ['console', 'shell'],
  },
  {
    id: 'package',
    title: 'Package',
    summary: 'A distributable unit of code with metadata and dependencies.',
    prerequisiteConceptIds: ['module-system'],
    aliases: ['library package', 'dependency'],
  },
  {
    id: 'runtime',
    title: 'Runtime',
    summary: 'The environment that executes a program, providing memory and services.',
    prerequisiteConceptIds: ['process', 'memory-model'],
    aliases: ['execution environment'],
  },
  {
    id: 'bit',
    title: 'Bit',
    summary: 'A single binary digit, the smallest unit of information.',
    prerequisiteConceptIds: ['binary'],
    aliases: ['binary digit'],
  },
  {
    id: 'byte',
    title: 'Byte',
    summary: 'A group of 8 bits, the addressable unit of most memory.',
    prerequisiteConceptIds: ['bit'],
    aliases: ['octet'],
  },

  // ── Programming fundamentals (expanded) ─────────────────────────────
  {
    id: 'expression-evaluation',
    title: 'Expression Evaluation',
    summary: 'Computing the value of an expression by applying operators to operands.',
    prerequisiteConceptIds: ['expression', 'operator'],
    aliases: ['evaluation'],
  },
  {
    id: 'integer-division',
    title: 'Integer Division',
    summary: 'Division that discards the remainder, returning a whole quotient.',
    prerequisiteConceptIds: ['operator', 'type'],
    aliases: ['floor division'],
  },
  {
    id: 'modulo',
    title: 'Modulo',
    summary: 'The remainder operator yielding what is left after integer division.',
    prerequisiteConceptIds: ['operator', 'integer-division'],
    aliases: ['remainder', 'mod'],
  },
  {
    id: 'off-by-one',
    title: 'Off-by-One Error',
    summary: 'A logic error from miscounting by one, common at loop boundaries.',
    prerequisiteConceptIds: ['for-loop', 'index'],
    aliases: ['fencepost error'],
  },
  {
    id: 'scope-chain',
    title: 'Scope Chain',
    summary: 'Nested scopes searched outward to resolve a name reference.',
    prerequisiteConceptIds: ['scope'],
    aliases: ['lexical scope lookup'],
  },
  {
    id: 'shadowing',
    title: 'Shadowing',
    summary: 'An inner declaration hiding an outer name of the same identifier.',
    prerequisiteConceptIds: ['scope'],
    aliases: ['name shadowing'],
  },
  {
    id: 'switch-statement',
    title: 'Switch Statement',
    summary: 'A multi-branch control structure dispatching on a single value.',
    prerequisiteConceptIds: ['conditional'],
    aliases: ['switch', 'case dispatch'],
  },
  {
    id: 'do-while',
    title: 'Do-While Loop',
    summary: 'A loop that tests the condition after the body, running at least once.',
    prerequisiteConceptIds: ['while-loop'],
    aliases: ['repeat-until'],
  },
  {
    id: 'break-continue',
    title: 'Break and Continue',
    summary: 'Loop control that exits early or skips to the next iteration.',
    prerequisiteConceptIds: ['loop'],
    aliases: ['loop control'],
  },
  {
    id: 'nested-loop',
    title: 'Nested Loop',
    summary: 'A loop inside another loop, common for grid and matrix traversal.',
    prerequisiteConceptIds: ['for-loop'],
    aliases: ['inner loop'],
  },
  {
    id: 'return-value',
    title: 'Return Value',
    summary: 'The value a function produces back to its caller.',
    prerequisiteConceptIds: ['function'],
    aliases: ['result'],
  },
  {
    id: 'side-effect',
    title: 'Side Effect',
    summary: 'An observable change beyond a function return value (I/O, mutation).',
    prerequisiteConceptIds: ['function', 'mutation'],
    aliases: ['effect'],
  },
  {
    id: 'pure-function',
    title: 'Pure Function',
    summary: 'A function with no side effects whose output depends only on inputs.',
    prerequisiteConceptIds: ['side-effect', 'function'],
    aliases: ['pure'],
  },
  {
    id: 'recursion-depth',
    title: 'Recursion Depth',
    summary: 'How deep nested recursive calls go before the base case.',
    prerequisiteConceptIds: ['recursion', 'stack-memory'],
    aliases: ['call depth'],
  },
  {
    id: 'tail-recursion',
    title: 'Tail Recursion',
    summary: 'Recursion where the recursive call is the final action, enabling optimization.',
    prerequisiteConceptIds: ['recursion'],
    aliases: ['tail call'],
  },
  {
    id: 'memoization',
    title: 'Memoization',
    summary: 'Caching results of expensive calls by input to avoid recomputation.',
    prerequisiteConceptIds: ['recursion', 'function'],
    aliases: ['function caching'],
  },

  // ── Data structures (expanded) ──────────────────────────────────────
  {
    id: 'dynamic-array',
    title: 'Dynamic Array',
    summary: 'An array that resizes itself by allocating a larger backing buffer.',
    prerequisiteConceptIds: ['array', 'memory-model'],
    aliases: ['resizable array', 'arraylist', 'vector'],
  },
  {
    id: 'arraylist-vs-linkedlist',
    title: 'Array vs Linked List',
    summary: 'Trade-offs between contiguous-index and pointer-linked storage.',
    prerequisiteConceptIds: ['array', 'linked-list'],
    aliases: ['list comparison'],
  },
  {
    id: 'list',
    title: 'List',
    summary: 'An ordered, indexable sequence of elements; the Python list is a dynamic array.',
    prerequisiteConceptIds: ['collection', 'array'],
    aliases: ['python list', 'sequence'],
  },
  {
    id: 'deque',
    title: 'Deque',
    summary: 'A double-ended queue supporting add and remove at both ends.',
    prerequisiteConceptIds: ['queue-ds'],
    aliases: ['double-ended queue'],
  },
  {
    id: 'circular-queue',
    title: 'Circular Queue',
    summary: 'A fixed-size queue reusing freed slots by wrapping indices.',
    prerequisiteConceptIds: ['queue-ds', 'array'],
    aliases: ['ring buffer'],
  },
  {
    id: 'priority-queue',
    title: 'Priority Queue',
    summary: 'A queue that dequeues the highest-priority element, not the oldest.',
    prerequisiteConceptIds: ['queue-ds', 'heap'],
    aliases: ['pq'],
  },
  {
    id: 'balanced-tree',
    title: 'Balanced Tree',
    summary: 'A tree kept roughly equal in depth to guarantee O(log n) operations.',
    prerequisiteConceptIds: ['bst'],
    aliases: ['self-balancing tree'],
  },
  {
    id: 'avl-tree',
    title: 'AVL Tree',
    summary: 'A self-balancing BST maintaining height balance via rotations.',
    prerequisiteConceptIds: ['balanced-tree', 'bst'],
    aliases: ['avl'],
  },
  {
    id: 'red-black-tree',
    title: 'Red-Black Tree',
    summary: 'A self-balancing BST using color rules for approximate balance.',
    prerequisiteConceptIds: ['balanced-tree', 'bst'],
    aliases: ['rb tree'],
  },
  {
    id: 'trie',
    title: 'Trie',
    summary: 'A prefix tree storing strings by shared character paths.',
    prerequisiteConceptIds: ['tree', 'string'],
    aliases: ['prefix tree'],
  },
  {
    id: 'graph-representation',
    title: 'Graph Representation',
    summary: 'Storing a graph as adjacency list or adjacency matrix.',
    prerequisiteConceptIds: ['graph', 'array', 'linked-list'],
    aliases: ['adjacency list', 'adjacency matrix'],
  },
  {
    id: 'directed-graph',
    title: 'Directed Graph',
    summary: 'A graph whose edges have direction, from one node to another.',
    prerequisiteConceptIds: ['graph'],
    aliases: ['digraph'],
  },
  {
    id: 'weighted-graph',
    title: 'Weighted Graph',
    summary: 'A graph whose edges carry costs or distances.',
    prerequisiteConceptIds: ['graph'],
    aliases: ['edge-weighted graph'],
  },
  {
    id: 'hash-function',
    title: 'Hash Function',
    summary: 'A function mapping data of arbitrary size to a fixed-size bucket index.',
    prerequisiteConceptIds: ['hashing', 'function'],
    aliases: ['hasher'],
  },
  {
    id: 'hash-collision',
    title: 'Hash Collision',
    summary: 'When two keys hash to the same bucket, requiring a resolution strategy.',
    prerequisiteConceptIds: ['hashing', 'hash-function'],
    aliases: ['collision'],
  },
  {
    id: 'load-factor',
    title: 'Load Factor',
    summary: 'The ratio of entries to buckets signaling when a hash table should resize.',
    prerequisiteConceptIds: ['hashing', 'hash-collision'],
    aliases: ['hash table fill'],
  },
  {
    id: 'bloom-filter',
    title: 'Bloom Filter',
    summary: 'A space-efficient probabilistic set for membership tests with false positives.',
    prerequisiteConceptIds: ['hashing', 'hash-function'],
    aliases: ['bloom'],
  },

  // ── Algorithms (expanded) ───────────────────────────────────────────
  {
    id: 'big-o',
    title: 'Big O Notation',
    summary: 'An upper bound on how runtime grows relative to input size.',
    prerequisiteConceptIds: ['complexity'],
    aliases: ['asymptotic upper bound'],
  },
  {
    id: 'big-omega',
    title: 'Big Omega Notation',
    summary: 'A lower bound on how runtime grows relative to input size.',
    prerequisiteConceptIds: ['complexity', 'big-o'],
    aliases: ['asymptotic lower bound'],
  },
  {
    id: 'big-theta',
    title: 'Big Theta Notation',
    summary: 'A tight bound matching both the upper and lower growth rates.',
    prerequisiteConceptIds: ['big-o', 'big-omega'],
    aliases: ['asymptotic tight bound'],
  },
  {
    id: 'amortized-cost',
    title: 'Amortized Cost',
    summary: 'Average cost per operation over a sequence, smoothing rare expensive ones.',
    prerequisiteConceptIds: ['complexity', 'big-o'],
    aliases: ['amortized analysis'],
  },
  {
    id: 'linear-search',
    title: 'Linear Search',
    summary: 'Scanning elements one by one until the target is found.',
    prerequisiteConceptIds: ['searching', 'array'],
    aliases: ['sequential search'],
  },
  {
    id: 'insertion-sort',
    title: 'Insertion Sort',
    summary: 'Sorting by inserting each element into its place in a growing sorted prefix.',
    prerequisiteConceptIds: ['sorting', 'array'],
    aliases: ['insert sort'],
  },
  {
    id: 'selection-sort',
    title: 'Selection Sort',
    summary: 'Sorting by repeatedly selecting the smallest remaining element.',
    prerequisiteConceptIds: ['sorting', 'array'],
    aliases: ['select sort'],
  },
  {
    id: 'bubble-sort',
    title: 'Bubble Sort',
    summary: 'Sorting by swapping adjacent out-of-order pairs until none remain.',
    prerequisiteConceptIds: ['sorting', 'array'],
    aliases: ['bubble'],
  },
  {
    id: 'merge-sort',
    title: 'Merge Sort',
    summary: 'A divide-and-conquer sort splitting, sorting halves, and merging.',
    prerequisiteConceptIds: ['sorting', 'divide-and-conquer'],
    aliases: ['mergesort'],
  },
  {
    id: 'quick-sort',
    title: 'Quick Sort',
    summary: 'A divide-and-conquer sort partitioning around a pivot recursively.',
    prerequisiteConceptIds: ['sorting', 'divide-and-conquer'],
    aliases: ['quicksort'],
  },
  {
    id: 'heap-sort',
    title: 'Heap Sort',
    summary: 'Sorting by building a heap and repeatedly extracting the max.',
    prerequisiteConceptIds: ['sorting', 'heap'],
    aliases: ['heapsort'],
  },
  {
    id: 'counting-sort',
    title: 'Counting Sort',
    summary: 'A non-comparison sort using value counts, linear for bounded ranges.',
    prerequisiteConceptIds: ['sorting', 'array'],
    aliases: ['count sort'],
  },
  {
    id: 'stability-sort',
    title: 'Sort Stability',
    summary: 'Whether equal keys retain their original relative order after sorting.',
    prerequisiteConceptIds: ['sorting'],
    aliases: ['stable sort'],
  },
  {
    id: 'in-place',
    title: 'In-Place Algorithm',
    summary: 'An algorithm using O(1) extra memory, mutating the input directly.',
    prerequisiteConceptIds: ['complexity', 'array'],
    aliases: ['in-place'],
  },
  {
    id: 'two-pointer',
    title: 'Two-Pointer Technique',
    summary: 'Using two indices moving over data to solve a problem in linear time.',
    prerequisiteConceptIds: ['array', 'algorithm'],
    aliases: ['two pointers'],
  },
  {
    id: 'sliding-window',
    title: 'Sliding Window',
    summary: 'Maintaining a moving sub-range to compute per-window results incrementally.',
    prerequisiteConceptIds: ['two-pointer', 'array'],
    aliases: ['window'],
  },
  {
    id: 'prefix-sum',
    title: 'Prefix Sum',
    summary: 'Precomputing cumulative sums to answer range-sum queries in O(1).',
    prerequisiteConceptIds: ['array', 'algorithm'],
    aliases: ['cumulative sum'],
  },
  {
    id: 'recurrence',
    title: 'Recurrence Relation',
    summary: 'Defining a value in terms of prior values, the math behind recursion and DP.',
    prerequisiteConceptIds: ['recursion', 'dynamic-programming'],
    aliases: ['recurrence'],
  },
  {
    id: 'dp-table',
    title: 'DP Table',
    summary: 'A bottom-up table storing subproblem answers to avoid recursion overhead.',
    prerequisiteConceptIds: ['dynamic-programming', 'array'],
    aliases: ['tabulation'],
  },
  {
    id: 'optimal-substructure',
    title: 'Optimal Substructure',
    summary: 'When an optimal solution contains optimal solutions to subproblems.',
    prerequisiteConceptIds: ['dynamic-programming', 'greedy'],
    aliases: ['optimality principle'],
  },
  {
    id: 'overlapping-subproblems',
    title: 'Overlapping Subproblems',
    summary: 'When a recursive solution recomputes the same subproblems repeatedly.',
    prerequisiteConceptIds: ['recursion', 'dynamic-programming'],
    aliases: ['repeated subproblems'],
  },
  {
    id: 'shortest-path',
    title: 'Shortest Path',
    summary: 'Finding the minimum-cost route between graph nodes.',
    prerequisiteConceptIds: ['graph', 'weighted-graph'],
    aliases: ['shortest route'],
  },
  {
    id: 'minimum-spanning-tree',
    title: 'Minimum Spanning Tree',
    summary: 'A least-total-weight set of edges connecting all graph nodes.',
    prerequisiteConceptIds: ['graph', 'weighted-graph'],
    aliases: ['mst'],
  },
  {
    id: 'topological-sort',
    title: 'Topological Sort',
    summary: 'An ordering of DAG nodes respecting all dependency edges.',
    prerequisiteConceptIds: ['graph', 'directed-graph'],
    aliases: ['topo sort'],
  },
  {
    id: 'union-find',
    title: 'Union-Find',
    summary: 'A disjoint-set structure for merging sets and testing membership in near-constant time.',
    prerequisiteConceptIds: ['graph', 'data-structure'],
    aliases: ['disjoint set', 'dsu'],
  },

  // ── Web development (expanded) ──────────────────────────────────────
  {
    id: 'semantic-html',
    title: 'Semantic HTML',
    summary: 'Using tags that convey meaning (article, nav, header) over generic divs.',
    prerequisiteConceptIds: ['html', 'element'],
    aliases: ['semantic markup'],
  },
  {
    id: 'form',
    title: 'Form',
    summary: 'An HTML element collecting and submitting user input.',
    prerequisiteConceptIds: ['html', 'element'],
    aliases: ['web form'],
  },
  {
    id: 'box-model',
    title: 'CSS Box Model',
    summary: 'How content, padding, border, and margin define an element space.',
    prerequisiteConceptIds: ['css'],
    aliases: ['box model'],
  },
  {
    id: 'flexbox',
    title: 'Flexbox',
    summary: 'A one-dimensional CSS layout model for distributing space along an axis.',
    prerequisiteConceptIds: ['css', 'box-model'],
    aliases: ['flex layout'],
  },
  {
    id: 'css-grid',
    title: 'CSS Grid',
    summary: 'A two-dimensional CSS layout model for rows and columns.',
    prerequisiteConceptIds: ['css', 'box-model'],
    aliases: ['grid layout'],
  },
  {
    id: 'responsive-design',
    title: 'Responsive Design',
    summary: 'Layouts adapting to different screen sizes with media queries.',
    prerequisiteConceptIds: ['css'],
    aliases: ['responsive web design'],
  },
  {
    id: 'selector',
    title: 'CSS Selector',
    summary: 'A pattern matching elements to which rules apply.',
    prerequisiteConceptIds: ['css', 'element'],
    aliases: ['css selector'],
  },
  {
    id: 'specificity',
    title: 'CSS Specificity',
    summary: 'The scoring that decides which rule wins when several target an element.',
    prerequisiteConceptIds: ['selector'],
    aliases: ['cascade priority'],
  },
  {
    id: 'dom-tree',
    title: 'DOM Tree',
    summary: 'The browser in-memory tree representing the parsed HTML document.',
    prerequisiteConceptIds: ['dom', 'tree'],
    aliases: ['document object model tree'],
  },
  {
    id: 'event',
    title: 'Event',
    summary: 'A notification that something happened, to which handlers can subscribe.',
    prerequisiteConceptIds: ['event-driven'],
    aliases: ['dom event'],
  },
  {
    id: 'event-listener',
    title: 'Event Listener',
    summary: 'A function registered to run when a specific event occurs.',
    prerequisiteConceptIds: ['event', 'function'],
    aliases: ['event handler'],
  },
  {
    id: 'event-bubbling',
    title: 'Event Bubbling',
    summary: 'Events propagating from the target up through ancestor elements.',
    prerequisiteConceptIds: ['event', 'dom-tree'],
    aliases: ['event propagation'],
  },
  {
    id: 'events',
    title: 'Events',
    summary: 'Notifications fired by the browser when something happens (click, input, load).',
    prerequisiteConceptIds: ['dom', 'function'],
    aliases: ['browser events', 'dom events'],
  },
  {
    id: 'event-listeners',
    title: 'Event Listeners',
    summary: 'Functions registered with addEventListener to run when an event fires.',
    prerequisiteConceptIds: ['events', 'function'],
    aliases: ['event handlers', 'addEventListener'],
  },
  {
    id: 'selectors',
    title: 'CSS Selectors',
    summary: 'Patterns that match DOM elements (#id, .class, tag, [attr]) used by CSS and querySelector.',
    prerequisiteConceptIds: ['css', 'dom'],
    aliases: ['css selector', 'query selector'],
  },
  {
    id: 'css-layout',
    title: 'CSS Layout',
    summary: 'Positioning and sizing elements: normal flow, flexbox, grid.',
    prerequisiteConceptIds: ['css', 'box-model'],
    aliases: ['layout', 'page layout'],
  },
  {
    id: 'client-server',
    title: 'Client-Server',
    summary: 'The architecture where a client requests services and a server provides them.',
    prerequisiteConceptIds: ['network'],
    aliases: ['client server model'],
  },
  {
    id: 'network',
    title: 'Network',
    summary: 'Computers exchanging data over wires or radio using protocols.',
    prerequisiteConceptIds: ['process'],
    aliases: ['computer network', 'networking'],
  },
  {
    id: 'status-codes',
    title: 'HTTP Status Codes',
    summary: 'Three-digit response codes grouped by class (2xx success, 4xx client error, 5xx server error).',
    prerequisiteConceptIds: ['http'],
    aliases: ['http status', 'response code'],
  },
  {
    id: 'crud',
    title: 'CRUD',
    summary: 'Create, Read, Update, Delete — the four basic persistence operations.',
    prerequisiteConceptIds: ['http', 'rest'],
    aliases: ['create read update delete'],
  },
  {
    id: 'javascript',
    title: 'JavaScript',
    summary: 'The programming language of the web browser; also used on servers via Node.js.',
    prerequisiteConceptIds: ['program'],
    aliases: ['js', 'ecmascript'],
  },
  {
    id: 'relational-database',
    title: 'Relational Database',
    summary: 'A database that stores data in related tables with rows and columns.',
    prerequisiteConceptIds: ['database', 'table'],
    aliases: ['rdbms', 'sql database'],
  },
  {
    id: 'b-tree',
    title: 'B-Tree',
    summary: 'A self-balancing search tree used by database indexes for O(log n) range and point lookups.',
    prerequisiteConceptIds: ['tree', 'binary-tree'],
    aliases: ['btree', 'balanced tree index'],
  },
  {
    id: 'indexing',
    title: 'Indexing',
    summary: 'Maintaining a sorted secondary structure on a column to speed lookups without full-table scans.',
    prerequisiteConceptIds: ['b-tree', 'database'],
    aliases: ['database index', 'secondary index'],
  },
  {
    id: 'isolation-levels',
    title: 'Transaction Isolation Levels',
    summary: 'Read Uncommitted, Read Committed, Repeatable Read, Serializable — controlling what concurrent transactions can see.',
    prerequisiteConceptIds: ['transaction', 'acid'],
    aliases: ['isolation level', 'transaction isolation'],
  },
  {
    id: 'memory-management',
    title: 'Memory Management',
    summary: 'Allocating and freeing memory: automatic (stack/GC) or manual (malloc/free).',
    prerequisiteConceptIds: ['memory-model', 'stack-ds', 'heap'],
    aliases: ['allocation', 'memory allocation'],
  },
  {
    id: 'assertion',
    title: 'Assertion',
    summary: 'A check that a condition holds, used in tests to verify expected behaviour.',
    prerequisiteConceptIds: ['testing', 'boolean-logic'],
    aliases: ['assert', 'expect'],
  },
  {
    id: 'mocking',
    title: 'Mocking',
    summary: 'Replacing a dependency with a fake that returns canned answers and records calls, to isolate the unit under test.',
    prerequisiteConceptIds: ['unit-testing', 'testing'],
    aliases: ['mock', 'test double', 'stub'],
  },
  {
    id: 'test-coverage',
    title: 'Test Coverage',
    summary: 'The percentage of code executed during tests; a floor (did this line run?) not a correctness proof.',
    prerequisiteConceptIds: ['unit-testing', 'testing'],
    aliases: ['coverage', 'code coverage'],
  },
  {
    id: 'refactoring',
    title: 'Refactoring',
    summary: 'Improving code structure without changing behaviour, with tests as the safety net.',
    prerequisiteConceptIds: ['unit-testing'],
    aliases: ['refactor', 'code restructuring'],
  },
  {
    id: 'tdd',
    title: 'Test-Driven Development',
    summary: 'Writing a failing test first, then the minimal code to pass it, then refactoring — red, green, refactor.',
    prerequisiteConceptIds: ['unit-testing', 'refactoring'],
    aliases: ['test first', 'red green refactor'],
  },
  {
    id: 'vector',
    title: 'Vector',
    summary: 'An ordered list of numbers; the core data structure for representing inputs, weights, and activations in ML.',
    prerequisiteConceptIds: ['array', 'literal'],
    aliases: ['array of numbers', 'feature vector'],
  },
  {
    id: 'matrix',
    title: 'Matrix',
    summary: 'A 2D array of numbers; matrix multiplication computes a whole layer of neurons in parallel.',
    prerequisiteConceptIds: ['vector', 'array'],
    aliases: ['2d array', 'tensor (2d)'],
  },
  {
    id: 'activation-function',
    title: 'Activation Function',
    summary: 'A non-linear function (relu, sigmoid, tanh) applied after the weighted sum; what makes depth expressive.',
    prerequisiteConceptIds: ['neural-network', 'function'],
    aliases: ['relu', 'nonlinearity'],
  },
  {
    id: 'weights',
    title: 'Weights',
    summary: 'Parameters that scale each input to a neuron; training adjusts weights to reduce loss.',
    prerequisiteConceptIds: ['neural-network', 'parameter'],
    aliases: ['model parameters', 'learnable weights'],
  },
  {
    id: 'bias',
    title: 'Bias',
    summary: 'A per-neuron parameter added to the weighted sum; shifts the decision threshold independent of inputs.',
    prerequisiteConceptIds: ['neural-network', 'parameter'],
    aliases: ['bias term', 'offset'],
  },
  {
    id: 'derivative',
    title: 'Derivative',
    summary: 'The instantaneous rate of change of a function; the gradient is the derivative extended to many variables.',
    prerequisiteConceptIds: ['function'],
    aliases: ['differential', 'rate of change'],
  },
  {
    id: 'promise',
    title: 'Promise',
    summary: 'A placeholder for a value available in the future, success or failure.',
    prerequisiteConceptIds: ['async', 'function'],
    aliases: ['future', 'thenable'],
  },
  {
    id: 'async-await',
    title: 'Async/Await',
    summary: 'Syntax making promise chains read like straight-line synchronous code.',
    prerequisiteConceptIds: ['promise', 'async'],
    aliases: ['async await'],
  },
  {
    id: 'callback',
    title: 'Callback',
    summary: 'A function passed to be invoked later, often on completion.',
    prerequisiteConceptIds: ['function', 'event-driven'],
    aliases: ['callback function'],
  },
  {
    id: 'websocket',
    title: 'WebSocket',
    summary: 'A full-duplex persistent connection between client and server.',
    prerequisiteConceptIds: ['http', 'networking'],
    aliases: ['ws'],
  },
  {
    id: 'cors',
    title: 'CORS',
    summary: 'The browser policy controlling cross-origin resource sharing.',
    prerequisiteConceptIds: ['http'],
    aliases: ['cross-origin resource sharing'],
  },
  {
    id: 'accessibility',
    title: 'Accessibility',
    summary: 'Designing so people with disabilities can perceive and use content.',
    prerequisiteConceptIds: ['html', 'semantic-html'],
    aliases: ['a11y'],
  },
  {
    id: 'component',
    title: 'Component',
    summary: 'A reusable UI unit combining markup, styles, and behavior.',
    prerequisiteConceptIds: ['frontend-architecture', 'function'],
    aliases: ['ui component'],
  },
  {
    id: 'state-management',
    title: 'State Management',
    summary: 'Coordinating shared UI data across a frontend application.',
    prerequisiteConceptIds: ['component', 'frontend-architecture'],
    aliases: ['app state'],
  },
  {
    id: 'virtual-dom',
    title: 'Virtual DOM',
    summary: 'An in-memory tree diffed against the real DOM to batch updates.',
    prerequisiteConceptIds: ['dom-tree', 'component'],
    aliases: ['vdom'],
  },

  // ── Backend (expanded) ──────────────────────────────────────────────
  {
    id: 'tcp-ip',
    title: 'TCP/IP',
    summary: 'The layered protocol stack underpinning internet communication.',
    prerequisiteConceptIds: ['networking'],
    aliases: ['internet protocol suite'],
  },
  {
    id: 'request-response',
    title: 'Request-Response Cycle',
    summary: 'The client sends a request, the server returns a response, then closes.',
    prerequisiteConceptIds: ['http', 'server'],
    aliases: ['http cycle'],
  },
  {
    id: 'status-code',
    title: 'HTTP Status Code',
    summary: 'A number indicating request outcome (2xx success, 4xx client, 5xx server).',
    prerequisiteConceptIds: ['http'],
    aliases: ['http status'],
  },
  {
    id: 'routing',
    title: 'Routing',
    summary: 'Mapping incoming requests to the handler for a URL path and method.',
    prerequisiteConceptIds: ['server', 'api'],
    aliases: ['route dispatch'],
  },
  {
    id: 'session',
    title: 'Session',
    summary: 'A server-side record tying requests to one user across a visit.',
    prerequisiteConceptIds: ['authentication', 'cookie'],
    aliases: ['user session'],
  },
  {
    id: 'cookie',
    title: 'Cookie',
    summary: 'A key-value pair the browser stores and sends with matching requests.',
    prerequisiteConceptIds: ['http'],
    aliases: ['http cookie'],
  },
  {
    id: 'jwt',
    title: 'JWT',
    summary: 'A compact, signed token carrying claims between parties.',
    prerequisiteConceptIds: ['authentication', 'json'],
    aliases: ['json web token'],
  },
  {
    id: 'hashing-passwords',
    title: 'Password Hashing',
    summary: 'Storing passwords as slow, salted hashes rather than plaintext.',
    prerequisiteConceptIds: ['authentication', 'hash-function'],
    aliases: ['password storage'],
  },
  {
    id: 'sql-injection',
    title: 'SQL Injection',
    summary: 'An attack injecting SQL through unsanitized input into a query.',
    prerequisiteConceptIds: ['sql', 'authentication'],
    aliases: ['injection attack'],
  },
  {
    id: 'xss',
    title: 'XSS',
    summary: 'Cross-site scripting: injecting scripts that run in another user browser.',
    prerequisiteConceptIds: ['html', 'security'],
    aliases: ['cross-site scripting'],
  },
  {
    id: 'message-queue',
    title: 'Message Queue',
    summary: 'A buffer decoupling producers from consumers via asynchronous messages.',
    prerequisiteConceptIds: ['server', 'queue-ds'],
    aliases: ['task queue'],
  },
  {
    id: 'worker',
    title: 'Worker',
    summary: 'A background process picking up jobs and running them off the main thread.',
    prerequisiteConceptIds: ['message-queue', 'concurrency'],
    aliases: ['background worker'],
  },
  {
    id: 'observability',
    title: 'Observability',
    summary: 'Logging, metrics, and tracing that let you understand running systems.',
    prerequisiteConceptIds: ['server', 'profiling'],
    aliases: ['telemetry'],
  },

  // ── Databases (expanded) ───────────────────────────────────────────
  {
    id: 'primary-key',
    title: 'Primary Key',
    summary: 'A column (or set) uniquely identifying each row in a table.',
    prerequisiteConceptIds: ['table'],
    aliases: ['pk'],
  },
  {
    id: 'join',
    title: 'Join',
    summary: 'Combining rows from two tables by matching a related column.',
    prerequisiteConceptIds: ['table', 'foreign-key'],
    aliases: ['sql join'],
  },
  {
    id: 'acid',
    title: 'ACID',
    summary: 'Atomicity, Consistency, Isolation, Durability: transaction guarantees.',
    prerequisiteConceptIds: ['transaction'],
    aliases: ['acid properties'],
  },
  {
    id: 'isolation-level',
    title: 'Isolation Level',
    summary: 'How visible intermediate transaction results are to others.',
    prerequisiteConceptIds: ['acid', 'transaction'],
    aliases: ['transaction isolation'],
  },
  {
    id: 'normal-form',
    title: 'Normal Form',
    summary: 'Rules reducing redundancy and anomaly risk in relational schemas.',
    prerequisiteConceptIds: ['normalization'],
    aliases: ['database normalization'],
  },
  {
    id: 'query-plan',
    title: 'Query Plan',
    summary: 'The strategy a database picks to execute a query (scan, index, join order).',
    prerequisiteConceptIds: ['index-db', 'join'],
    aliases: ['execution plan'],
  },
  {
    id: 'document-store',
    title: 'Document Store',
    summary: 'A NoSQL database storing flexible JSON-like documents by key.',
    prerequisiteConceptIds: ['nosql', 'json'],
    aliases: ['document database'],
  },
  {
    id: 'key-value-store',
    title: 'Key-Value Store',
    summary: 'A NoSQL database mapping keys to values with simple get/set.',
    prerequisiteConceptIds: ['nosql', 'map'],
    aliases: ['kv store'],
  },
  {
    id: 'redis-cache',
    title: 'Redis Cache',
    summary: 'An in-memory key-value store used for fast caching and sessions.',
    prerequisiteConceptIds: ['key-value-store', 'caching'],
    aliases: ['redis'],
  },

  // ── Systems programming (expanded) ──────────────────────────────────
  {
    id: 'pointer-arithmetic',
    title: 'Pointer Arithmetic',
    summary: 'Computing new pointers by adding offsets to a base address.',
    prerequisiteConceptIds: ['pointer', 'manual-memory'],
    aliases: ['pointer math'],
  },
  {
    id: 'dangling-pointer',
    title: 'Dangling Pointer',
    summary: 'A pointer to memory that has been freed, using it is undefined behavior.',
    prerequisiteConceptIds: ['pointer', 'manual-memory'],
    aliases: ['use after free'],
  },
  {
    id: 'memory-leak',
    title: 'Memory Leak',
    summary: 'Allocated memory never freed, gradually exhausting available memory.',
    prerequisiteConceptIds: ['manual-memory', 'heap-memory'],
    aliases: ['leak'],
  },
  {
    id: 'buffer-overflow',
    title: 'Buffer Overflow',
    summary: 'Writing past the end of an array into adjacent memory, a classic security bug.',
    prerequisiteConceptIds: ['array', 'manual-memory'],
    aliases: ['overflow'],
  },
  {
    id: 'undefined-behavior',
    title: 'Undefined Behavior',
    summary: 'Actions the language standard leaves unspecified, letting compilers do anything.',
    prerequisiteConceptIds: ['manual-memory', 'compilation'],
    aliases: ['ub'],
  },
  {
    id: 'struct',
    title: 'Struct',
    summary: 'A user-defined type grouping named fields laid out in memory.',
    prerequisiteConceptIds: ['type', 'memory-model'],
    aliases: ['structure'],
  },
  {
    id: 'header-file',
    title: 'Header File',
    summary: 'A file declaring interfaces that source files include to share declarations.',
    prerequisiteConceptIds: ['compilation', 'module-system'],
    aliases: ['header'],
  },
  {
    id: 'linking',
    title: 'Linking',
    summary: 'Combining compiled object files and libraries into an executable.',
    prerequisiteConceptIds: ['compilation'],
    aliases: ['linker'],
  },
  {
    id: 'move-semantics',
    title: 'Move Semantics',
    summary: 'Transferring ownership of a resource instead of copying it.',
    prerequisiteConceptIds: ['ownership', 'manual-memory'],
    aliases: ['move'],
  },
  {
    id: 'raii',
    title: 'RAII',
    summary: 'Tying resource lifetimes to object lifetimes so cleanup is automatic.',
    prerequisiteConceptIds: ['ownership', 'object'],
    aliases: ['resource acquisition is initialization'],
  },
  {
    id: 'trait',
    title: 'Trait',
    summary: 'A named set of methods a type can implement to gain shared behavior.',
    prerequisiteConceptIds: ['ownership', 'object-oriented-design'],
    aliases: ['interface trait'],
  },
  {
    id: 'pattern-matching',
    title: 'Pattern Matching',
    summary: 'Selecting behavior by structural shape of data rather than chains of equals.',
    prerequisiteConceptIds: ['conditional', 'recursion'],
    aliases: ['match'],
  },
  {
    id: 'result-option',
    title: 'Result/Option Types',
    summary: 'Explicit success/failure or presence/absence types, replacing exceptions or null.',
    prerequisiteConceptIds: ['type', 'error-handling'],
    aliases: ['option', 'result'],
  },
  {
    id: 'data-race',
    title: 'Data Race',
    summary: 'When two threads access data concurrently and at least one writes, without sync.',
    prerequisiteConceptIds: ['thread', 'synchronization'],
    aliases: ['race condition'],
  },
  {
    id: 'mutex',
    title: 'Mutex',
    summary: 'A lock granting a thread exclusive access to a shared resource.',
    prerequisiteConceptIds: ['synchronization', 'thread'],
    aliases: ['lock'],
  },
  {
    id: 'channel',
    title: 'Channel',
    summary: 'A typed conduit for sending values between concurrent tasks safely.',
    prerequisiteConceptIds: ['concurrency', 'message-queue'],
    aliases: ['go channel'],
  },
  {
    id: 'atomic-operation',
    title: 'Atomic Operation',
    summary: 'An operation that appears indivisible to other threads, no interleaving.',
    prerequisiteConceptIds: ['thread', 'synchronization'],
    aliases: ['atomic'],
  },
  {
    id: 'deadlock',
    title: 'Deadlock',
    summary: 'Two or more threads each waiting on the other, blocking forever.',
    prerequisiteConceptIds: ['mutex', 'thread'],
    aliases: ['deadly embrace'],
  },

  // ── Software engineering (expanded) ─────────────────────────────────
  {
    id: 'pull-request',
    title: 'Pull Request',
    summary: 'A proposal to merge a branch into another, reviewed before integration.',
    prerequisiteConceptIds: ['branch', 'code-review'],
    aliases: ['pr', 'merge request'],
  },
  {
    id: 'merge-conflict',
    title: 'Merge Conflict',
    summary: 'When two changes touch the same lines and must be reconciled by hand.',
    prerequisiteConceptIds: ['branch', 'version-control'],
    aliases: ['conflict'],
  },
  {
    id: 'rebase',
    title: 'Rebase',
    summary: 'Replaying a branch commits on a new base to maintain linear history.',
    prerequisiteConceptIds: ['branch', 'commit'],
    aliases: ['git rebase'],
  },
  {
    id: 'test-driven',
    title: 'Test-Driven Development',
    summary: 'Writing a failing test first, then code to pass it, then refactoring.',
    prerequisiteConceptIds: ['unit-testing', 'refactoring'],
    aliases: ['tdd'],
  },
  {
    id: 'mock',
    title: 'Mock',
    summary: 'A stand-in replacing a dependency in tests to isolate the unit under test.',
    prerequisiteConceptIds: ['unit-testing'],
    aliases: ['test double'],
  },
  {
    id: 'coverage',
    title: 'Test Coverage',
    summary: 'The fraction of code exercised by tests, a signal (not proof) of thoroughness.',
    prerequisiteConceptIds: ['unit-testing'],
    aliases: ['code coverage'],
  },
  {
    id: 'solid',
    title: 'SOLID',
    summary: 'Five design principles for maintainable object-oriented code.',
    prerequisiteConceptIds: ['object-oriented-design', 'design-pattern'],
    aliases: ['solid principles'],
  },
  {
    id: 'single-responsibility',
    title: 'Single Responsibility',
    summary: 'A class should have one reason to change, one job.',
    prerequisiteConceptIds: ['solid'],
    aliases: ['srp'],
  },
  {
    id: 'dependency-inversion',
    title: 'Dependency Inversion',
    summary: 'Depend on abstractions, not concretions, so high-level policy is decoupled.',
    prerequisiteConceptIds: ['solid'],
    aliases: ['di'],
  },
  {
    id: 'dry',
    title: 'DRY',
    summary: "Don't Repeat Yourself: every knowledge piece has a single authoritative source.",
    prerequisiteConceptIds: ['refactoring'],
    aliases: ['dont repeat yourself'],
  },
  {
    id: 'code-smell',
    title: 'Code Smell',
    summary: 'A surface hint that deeper design problems may lurk in the code.',
    prerequisiteConceptIds: ['refactoring', 'code-review'],
    aliases: ['smell'],
  },
  {
    id: 'technical-debt',
    title: 'Technical Debt',
    summary: 'The future cost of shortcuts taken now for speed; must be repaid with interest.',
    prerequisiteConceptIds: ['refactoring'],
    aliases: ['tech debt'],
  },
  {
    id: 'documentation',
    title: 'Documentation',
    summary: 'Written explanation helping users and maintainers understand code.',
    prerequisiteConceptIds: ['code-review'],
    aliases: ['docs'],
  },
  {
    id: 'semantic-versioning',
    title: 'Semantic Versioning',
    summary: 'A MAJOR.MINOR.PATCH scheme signaling the kind and impact of changes.',
    prerequisiteConceptIds: ['version-control'],
    aliases: ['semver'],
  },

  // ── AI / ML (expanded) ──────────────────────────────────────────────
  {
    id: 'regression',
    title: 'Regression',
    summary: 'Predicting a continuous value from features, the simplest supervised task.',
    prerequisiteConceptIds: ['supervised-learning'],
    aliases: ['linear regression'],
  },
  {
    id: 'classification',
    title: 'Classification',
    summary: 'Predicting a discrete label from features, the other core supervised task.',
    prerequisiteConceptIds: ['supervised-learning'],
    aliases: ['classifier'],
  },
  {
    id: 'loss-function',
    title: 'Loss Function',
    summary: 'A measure of how wrong predictions are, minimized during training.',
    prerequisiteConceptIds: ['training', 'function'],
    aliases: ['objective function'],
  },
  {
    id: 'gradient-descent',
    title: 'Gradient Descent',
    summary: 'Iteratively nudging parameters down the loss slope toward a minimum.',
    prerequisiteConceptIds: ['training', 'loss-function'],
    aliases: ['gd'],
  },
  {
    id: 'backpropagation',
    title: 'Backpropagation',
    summary: 'Computing gradients through a network by applying the chain rule backward.',
    prerequisiteConceptIds: ['training', 'neural-network'],
    aliases: ['backprop'],
  },
  {
    id: 'overfitting',
    title: 'Overfitting',
    summary: 'When a model memorizes training data and generalizes poorly to new data.',
    prerequisiteConceptIds: ['training', 'supervised-learning'],
    aliases: ['overfit'],
  },
  {
    id: 'regularization',
    title: 'Regularization',
    summary: 'Penalizing model complexity to reduce overfitting.',
    prerequisiteConceptIds: ['overfitting'],
    aliases: ['weight decay'],
  },
  {
    id: 'train-test-split',
    title: 'Train/Test Split',
    summary: 'Holding out data to honestly evaluate generalization, not training on it.',
    prerequisiteConceptIds: ['supervised-learning'],
    aliases: ['validation split'],
  },
  {
    id: 'inference',
    title: 'Inference',
    summary: 'Using a trained model to produce predictions for new inputs.',
    prerequisiteConceptIds: ['training', 'model'],
    aliases: ['model inference'],
  },
  {
    id: 'vector-database',
    title: 'Vector Database',
    summary: 'A store optimized for similarity search over embedding vectors.',
    prerequisiteConceptIds: ['embedding', 'nosql'],
    aliases: ['vector store'],
  },
  {
    id: 'ai-agent',
    title: 'AI Agent',
    summary: 'A system that plans, uses tools, and acts toward a goal using an LLM.',
    prerequisiteConceptIds: ['llm', 'function'],
    aliases: ['agent', 'autonomous agent'],
  },
  {
    id: 'rag',
    title: 'Retrieval-Augmented Generation',
    summary: 'Grounding an LLM answer by retrieving relevant context first.',
    prerequisiteConceptIds: ['llm', 'vector-database'],
    aliases: ['rag'],
  },
  {
    id: 'fine-tuning',
    title: 'Fine-Tuning',
    summary: 'Continuing training of a pretrained model on task-specific data.',
    prerequisiteConceptIds: ['training', 'llm'],
    aliases: ['fine tune'],
  },

  // ── Mobile development ─────────────────────────────────────────────
  {
    id: 'mobile-lifecycle',
    title: 'App Lifecycle',
    summary: 'The stages a mobile app passes through (foreground, background, resume).',
    prerequisiteConceptIds: ['component', 'event-driven'],
    aliases: ['activity lifecycle'],
  },
  {
    id: 'intent',
    title: 'Intent',
    summary: 'A description of an action to perform, central to Android navigation.',
    prerequisiteConceptIds: ['event', 'mobile-lifecycle'],
    aliases: ['android intent'],
  },
  {
    id: 'mobile-ui',
    title: 'Mobile UI',
    summary: 'Touch-first interface design with gestures, density, and safe areas.',
    prerequisiteConceptIds: ['component', 'responsive-design'],
    aliases: ['mobile interface'],
  },
  {
    id: 'permissions',
    title: 'Permissions',
    summary: 'Runtime consent for app access to sensitive resources like location.',
    prerequisiteConceptIds: ['authentication', 'security'],
    aliases: ['app permissions'],
  },
  {
    id: 'platform-channel',
    title: 'Platform Channel',
    summary: 'A bridge for cross-platform frameworks to call native OS APIs.',
    prerequisiteConceptIds: ['api', 'concurrency'],
    aliases: ['method channel'],
  },

  // ── Game development ────────────────────────────────────────────────
  {
    id: 'rendering',
    title: 'Rendering',
    summary: 'Producing images from scene data, geometry, and lighting.',
    prerequisiteConceptIds: ['game-loop'],
    aliases: ['render pipeline'],
  },
  {
    id: 'collision-detection',
    title: 'Collision Detection',
    summary: 'Detecting when game objects intersect to trigger responses.',
    prerequisiteConceptIds: ['game-loop'],
    aliases: ['collision'],
  },
  {
    id: 'entity-component',
    title: 'Entity-Component System',
    summary: 'Modeling objects as entities of pluggable components rather than inheritance.',
    prerequisiteConceptIds: ['object-oriented-design', 'game-loop'],
    aliases: ['ecs'],
  },
  {
    id: 'physics-simulation',
    title: 'Physics Simulation',
    summary: 'Numerically integrating motion, gravity, and forces each frame.',
    prerequisiteConceptIds: ['game-loop', 'function'],
    aliases: ['game physics'],
  },

  // ── Advanced CS (expanded) ──────────────────────────────────────────
  {
    id: 'lexer',
    title: 'Lexer',
    summary: 'A tokenizer converting source text into a stream of tokens.',
    prerequisiteConceptIds: ['parser', 'string'],
    aliases: ['tokenizer', 'scanner'],
  },
  {
    id: 'grammar',
    title: 'Grammar',
    summary: 'A formal set of rules defining the valid structure of a language.',
    prerequisiteConceptIds: ['parser', 'ast'],
    aliases: ['syntax grammar'],
  },
  {
    id: 'interpreter',
    title: 'Interpreter',
    summary: 'A program that executes source code directly without a separate compile step.',
    prerequisiteConceptIds: ['interpretation', 'ast'],
    aliases: ['evaluator'],
  },
  {
    id: 'compiler-optimization',
    title: 'Compiler Optimization',
    summary: 'Transforming code to run faster or use less memory without changing behavior.',
    prerequisiteConceptIds: ['compilation', 'profiling'],
    aliases: ['optimization'],
  },
  {
    id: 'garbage-collection',
    title: 'Garbage Collection',
    summary: 'Automatic reclamation of memory no longer reachable by the program.',
    prerequisiteConceptIds: ['memory-model', 'runtime'],
    aliases: ['gc'],
  },
  {
    id: 'consensus',
    title: 'Consensus',
    summary: 'An algorithm letting distributed nodes agree despite failures.',
    prerequisiteConceptIds: ['distributed-systems'],
    aliases: ['consensus protocol'],
  },
  {
    id: 'mapreduce',
    title: 'MapReduce',
    summary: 'A model processing large datasets with a map then a reduce step across nodes.',
    prerequisiteConceptIds: ['distributed-systems', 'function'],
    aliases: ['map reduce'],
  },
  {
    id: 'cap-theorem',
    title: 'CAP Theorem',
    summary: 'A distributed system can guarantee at most two of Consistency, Availability, Partition tolerance.',
    prerequisiteConceptIds: ['distributed-systems'],
    aliases: ['cap'],
  },
  {
    id: 'symmetric-encryption',
    title: 'Symmetric Encryption',
    summary: 'Encryption where the same key is used to encrypt and decrypt.',
    prerequisiteConceptIds: ['cryptography'],
    aliases: ['shared-key encryption'],
  },
  {
    id: 'asymmetric-encryption',
    title: 'Asymmetric Encryption',
    summary: 'Encryption using a public key to encrypt and a private key to decrypt.',
    prerequisiteConceptIds: ['cryptography'],
    aliases: ['public-key encryption'],
  },
  {
    id: 'hash-integrity',
    title: 'Cryptographic Hash',
    summary: 'A one-way fingerprint of data used to detect tampering.',
    prerequisiteConceptIds: ['hash-function', 'cryptography'],
    aliases: ['digest'],
  },
  {
    id: 'threat-model',
    title: 'Threat Model',
    summary: 'A structured description of assets, adversaries, and attack surfaces.',
    prerequisiteConceptIds: ['cryptography', 'security'],
    aliases: ['security model'],
  },
  {
    id: 'cache',
    title: 'Cache',
    summary: 'A fast, small store that keeps recently or frequently used data so future reads avoid the slow path; trades memory for speed.',
    prerequisiteConceptIds: ['memory-model'],
    aliases: ['caching', 'cache layer'],
  },
  {
    id: 'breakpoint',
    title: 'Breakpoint',
    summary: 'A marker that pauses execution at a line so a debugger can inspect state before the program continues; the entry point of interactive debugging.',
    prerequisiteConceptIds: ['debugging'],
    aliases: ['break point', 'pause point'],
  },
  {
    id: 'compiler',
    title: 'Compiler',
    summary: 'A program that translates source code into a lower-level form (machine code or bytecode) ahead of, or before, execution.',
    prerequisiteConceptIds: ['compilation', 'ast'],
    aliases: ['transpiler', 'language processor'],
  },
  {
    id: 'event-loop',
    title: 'Event Loop',
    summary: 'The runtime loop that drains the task and microtask queues onto a single call stack, enabling non-blocking concurrency in JS.',
    prerequisiteConceptIds: ['async', 'callback'],
    aliases: ['run loop', 'message loop'],
  },
  {
    id: 'task-queue',
    title: 'Task Queue',
    summary: 'A FIFO of macrotasks (timers, I/O callbacks) the event loop drains one per turn after the stack is empty.',
    prerequisiteConceptIds: ['event-loop', 'queue-ds'],
    aliases: ['macrotask queue', 'callback queue'],
  },
  {
    id: 'microtask',
    title: 'Microtask',
    summary: 'A high-priority job (promise continuations) drained fully before any macrotask, giving promises lower latency than timers.',
    prerequisiteConceptIds: ['promise', 'event-loop'],
    aliases: ['microtask queue', 'jobs queue'],
  },
  {
    id: 'oauth',
    title: 'OAuth',
    summary: 'A delegated-authorization protocol: a user grants a third party scoped access without sharing their password.',
    prerequisiteConceptIds: ['authentication', 'authorization'],
    aliases: ['oauth2', 'delegated auth'],
  },
  {
    id: 'cookie',
    title: 'Cookie',
    summary: 'A key-value string the server sets and the browser attaches to later requests to the same origin; the basis of stateful sessions.',
    prerequisiteConceptIds: ['http'],
    aliases: ['http cookie', 'browser cookie'],
  },
  {
    id: 'csrf',
    title: 'CSRF',
    summary: 'Cross-Site Request Forgery: tricking a logged-in browser into issuing a state-changing request it did not intend.',
    prerequisiteConceptIds: ['cookie', 'security'],
    aliases: ['cross-site request forgery', 'xsrf'],
  },
  {
    id: 'password-hashing',
    title: 'Password Hashing',
    summary: 'Storing a slow, salted one-way digest instead of the plaintext password so a database leak reveals no credentials.',
    prerequisiteConceptIds: ['hashing-passwords', 'hash-function'],
    aliases: ['salted hashing', 'slow hashing'],
  },
  {
    id: 'cdn',
    title: 'CDN',
    summary: 'A geographically distributed cache of static assets that serves users from a nearby edge instead of the origin server.',
    prerequisiteConceptIds: ['cache', 'networking'],
    aliases: ['content delivery network', 'edge network'],
  },
  {
    id: 'load-balancing',
    title: 'Load Balancing',
    summary: 'Distributing incoming requests across multiple server instances so no single host is a bottleneck or single point of failure.',
    prerequisiteConceptIds: ['client-server', 'networking'],
    aliases: ['load balancer', 'request distribution'],
  },
  {
    id: 'horizontal-scaling',
    title: 'Horizontal Scaling',
    summary: 'Adding more machine instances to handle load, versus making one machine bigger (vertical); enabled by stateless design.',
    prerequisiteConceptIds: ['distributed-systems'],
    aliases: ['scaling out', 'scale-out'],
  },
  {
    id: 'sharding',
    title: 'Sharding',
    summary: 'Partitioning a dataset across multiple databases so each shard holds a horizontal slice, enabling writes to scale.',
    prerequisiteConceptIds: ['distributed-systems', 'database'],
    aliases: ['data partitioning', 'horizontal partitioning'],
  },
  {
    id: 'cache-invalidation',
    title: 'Cache Invalidation',
    summary: 'Deciding when a cached value is stale and must be refreshed or evicted; the hardest problem in caching (write-through, TTL, write-behind).',
    prerequisiteConceptIds: ['cache', 'redis-cache'],
    aliases: ['cache eviction', 'cache coherence'],
  },
  {
    id: 'condition-variable',
    title: 'Condition Variable',
    summary: 'A synchronization primitive a thread waits on until another thread signals a condition became true, used with a mutex.',
    prerequisiteConceptIds: ['mutex', 'thread', 'concurrency'],
    aliases: ['condvar', 'condition'],
  },
  {
    id: 'read-write-lock',
    title: 'Read-Write Lock',
    summary: 'A lock allowing many concurrent readers or one exclusive writer, improving throughput when reads dominate.',
    prerequisiteConceptIds: ['mutex', 'concurrency'],
    aliases: ['rwlock', 'reader-writer lock'],
  },
  {
    id: 'codegen',
    title: 'Code Generation',
    summary: 'The compiler phase that emits target (machine or bytecode) instructions from an optimized intermediate representation.',
    prerequisiteConceptIds: ['ast', 'compiler'],
    aliases: ['code generation', 'emit'],
  },
  {
    id: 'just-in-time',
    title: 'Just-In-Time Compilation',
    summary: 'Compiling hot bytecode to native code at runtime so interpreted languages get near-compiled speed via dynamic optimization.',
    prerequisiteConceptIds: ['codegen', 'interpreter'],
    aliases: ['jit', 'dynamic compilation'],
  },
  {
    id: 'single-step',
    title: 'Stepping',
    summary: 'Executing one statement (or one function call) at a time under a debugger to follow control flow and inspect state changes.',
    prerequisiteConceptIds: ['breakpoint', 'debugging'],
    aliases: ['single-step', 'step into', 'step over'],
  },
  {
    id: 'stack-trace',
    title: 'Stack Trace',
    summary: 'The chain of active function frames printed when an error occurs, showing the call path from the crash back to the entry point.',
    prerequisiteConceptIds: ['stack-ds', 'debugging'],
    aliases: ['backtrace', 'traceback'],
  },
  {
    id: 'profiler',
    title: 'Profiler',
    summary: 'A tool that samples a running program to attribute time or memory to functions, revealing where optimization pays off.',
    prerequisiteConceptIds: ['debugging', 'performance'],
    aliases: ['profiling', 'sampling profiler'],
  },
  {
    id: 'watch-expression',
    title: 'Watch Expression',
    summary: 'An expression a debugger re-evaluates on each step, letting you track how a value or condition evolves through execution.',
    prerequisiteConceptIds: ['single-step', 'debugging'],
    aliases: ['watch', 'data breakpoint'],
  },
  {
    id: 'singleton',
    title: 'Singleton',
    summary: 'A creational pattern guaranteeing a class has exactly one instance with a single global access point.',
    prerequisiteConceptIds: ['design-pattern', 'encapsulation'],
    aliases: ['singleton pattern'],
  },
  {
    id: 'factory-method',
    title: 'Factory Method',
    summary: 'A creational pattern that defers which concrete class to instantiate to a subclass or function, decoupling creation from use.',
    prerequisiteConceptIds: ['design-pattern', 'polymorphism'],
    aliases: ['factory', 'factory pattern'],
  },
  {
    id: 'observer',
    title: 'Observer',
    summary: 'A behavioral pattern where subjects notify subscribed observers of state changes, the basis of event-driven and reactive systems.',
    prerequisiteConceptIds: ['design-pattern', 'event-driven'],
    aliases: ['observer pattern', 'pub-sub'],
  },
  {
    id: 'strategy',
    title: 'Strategy',
    summary: 'A behavioral pattern that encapsulates interchangeable algorithms behind a common interface, selected at runtime.',
    prerequisiteConceptIds: ['design-pattern', 'polymorphism'],
    aliases: ['strategy pattern', 'policy'],
  },
  {
    id: 'probability',
    title: 'Probability',
    summary: 'A number in [0,1] measuring how likely an event is; the foundation of statistical reasoning and probabilistic ML models.',
    prerequisiteConceptIds: ['statistics'],
    aliases: ['prob'],
  },
  {
    id: 'probability-distribution',
    title: 'Probability Distribution',
    summary: 'A function assigning a probability to each outcome, describing how a random variable spreads its mass across values.',
    prerequisiteConceptIds: ['probability', 'statistics'],
    aliases: ['distribution', 'density'],
  },
  {
    id: 'mean',
    title: 'Mean',
    summary: 'The expected value — the sum of values weighted by their probability; the center of mass of a distribution.',
    prerequisiteConceptIds: ['probability-distribution'],
    aliases: ['expected value', 'average'],
  },
  {
    id: 'variance',
    title: 'Variance',
    summary: 'The expected squared deviation from the mean; measures how spread out a distribution is (std dev is its square root).',
    prerequisiteConceptIds: ['mean', 'probability-distribution'],
    aliases: ['spread', 'second moment'],
  },
  {
    id: 'bayes-theorem',
    title: 'Bayes Theorem',
    summary: 'Updates a prior belief with evidence to get a posterior: P(A|B) = P(B|A)P(A)/P(B); the engine of belief revision.',
    prerequisiteConceptIds: ['probability', 'statistics'],
    aliases: ['bayes', 'bayesian'],
  },
  {
    id: 'dot-product',
    title: 'Dot Product',
    summary: 'The sum of element-wise products of two vectors; geometrically proportional to their alignment (cosine of the angle).',
    prerequisiteConceptIds: ['vector', 'matrix'],
    aliases: ['inner product', 'scalar product'],
  },
  {
    id: 'matrix-multiplication',
    title: 'Matrix Multiplication',
    summary: 'Combining two matrices so each output cell is a dot product of a row and column; the operation a neural layer performs.',
    prerequisiteConceptIds: ['matrix', 'dot-product'],
    aliases: ['matmul', 'matrix product'],
  },
  {
    id: 'transpose',
    title: 'Transpose',
    summary: 'Flipping a matrix over its diagonal so rows become columns; used in matmul, gradients, and symmetry.',
    prerequisiteConceptIds: ['matrix'],
    aliases: ['matrix transpose'],
  },
  {
    id: 'determinant',
    title: 'Determinant',
    summary: 'A scalar capturing how a linear transform scales volume; zero means the transform collapses space (non-invertible).',
    prerequisiteConceptIds: ['matrix', 'transpose'],
    aliases: ['det'],
  },
  {
    id: 'eigenvalue',
    title: 'Eigenvalue',
    summary: 'A scalar λ for which Av = λv has a non-zero eigenvector v; the directions a transform merely stretches rather than rotates.',
    prerequisiteConceptIds: ['matrix', 'determinant'],
    aliases: ['eigen', 'characteristic root'],
  },
  {
    id: 'attention',
    title: 'Attention',
    summary: 'A mechanism computing weighted averages of values where weights come from query-key similarity, letting a model focus on relevant context.',
    prerequisiteConceptIds: ['dot-product', 'matrix-multiplication'],
    aliases: ['attention mechanism'],
  },
  {
    id: 'self-attention',
    title: 'Self-Attention',
    summary: 'Attention where queries, keys, and values all come from the same input sequence, letting each token weigh every other token.',
    prerequisiteConceptIds: ['attention', 'embedding'],
    aliases: ['scaled dot-product attention'],
  },
  {
    id: 'tokenization',
    title: 'Tokenization',
    summary: 'Splitting text into discrete units (subword pieces) a model can map to embeddings; the input boundary of an LLM.',
    prerequisiteConceptIds: ['embedding', 'string'],
    aliases: ['tokenize', 'subword segmentation'],
  },
  {
    id: 'positional-encoding',
    title: 'Positional Encoding',
    summary: 'Adding position-dependent signals to embeddings so self-attention (which is orderless) can recover sequence order.',
    prerequisiteConceptIds: ['self-attention', 'embedding'],
    aliases: ['position encoding'],
  },
  {
    id: 'multi-head-attention',
    title: 'Multi-Head Attention',
    summary: 'Running several attention computations in parallel on different projections and concatenating, letting a model attend to multiple relations at once.',
    prerequisiteConceptIds: ['self-attention', 'attention'],
    aliases: ['multihead attention'],
  },
]

export const CONCEPT_BY_ID: Record<string, Concept> = Object.fromEntries(
  CONCEPTS.map((concept) => [concept.id, concept]),
)

export function getConcept(id: string): Concept | undefined {
  return CONCEPT_BY_ID[id]
}

export function listConcepts(): Concept[] {
  return CONCEPTS
}
