/**
 * Cambric Labs — Concept Catalog
 *
 * Concepts are language-agnostic units of knowledge (e.g. "variable",
 * "for-loop", "ownership"). They form a directed acyclic graph via
 * prerequisite edges. The adaptive scheduler uses this graph to ensure a
 * learner never meets a concept before its prerequisites.
 *
 * Aliases are used by the semantic-duplicate detector so that, e.g.,
 * "function" and "method" and "procedure" can be recognized as related
 * across languages without false-positive duplicate flags.
 */
import type { Concept } from '../types'

export const CONCEPTS: Concept[] = [
  {
    id: 'program',
    title: 'Program',
    summary: 'A sequence of instructions a computer executes.',
    prerequisiteConceptIds: [],
    aliases: ['code', 'script'],
  },
  {
    id: 'statement',
    title: 'Statement',
    summary: 'A single instruction that performs an action.',
    prerequisiteConceptIds: ['program'],
    aliases: ['instruction'],
  },
  {
    id: 'expression',
    title: 'Expression',
    summary: 'A piece of code that evaluates to a value.',
    prerequisiteConceptIds: ['statement'],
    aliases: ['value-producing code'],
  },
  {
    id: 'variable',
    title: 'Variable',
    summary: 'A named container that stores a value.',
    prerequisiteConceptIds: ['statement'],
    aliases: ['binding', 'name'],
  },
  {
    id: 'assignment',
    title: 'Assignment',
    summary: 'Storing a value into a variable.',
    prerequisiteConceptIds: ['variable'],
    aliases: ['reassignment'],
  },
  {
    id: 'type',
    title: 'Type',
    summary: 'A classification of data that determines valid operations.',
    prerequisiteConceptIds: ['variable'],
    aliases: ['data type'],
  },
  {
    id: 'literal',
    title: 'Literal',
    summary: 'A fixed value written directly in source, e.g. 42 or "hi".',
    prerequisiteConceptIds: ['expression'],
    aliases: ['constant value'],
  },
  {
    id: 'operator',
    title: 'Operator',
    summary: 'A symbol performing an operation on one or more operands.',
    prerequisiteConceptIds: ['expression'],
    aliases: ['operation'],
  },
  {
    id: 'function',
    title: 'Function',
    summary: 'A reusable, named block of code that takes inputs and returns a result.',
    prerequisiteConceptIds: ['variable', 'statement'],
    aliases: ['method', 'procedure', 'subroutine'],
  },
  {
    id: 'parameter',
    title: 'Parameter',
    summary: 'A named input a function accepts.',
    prerequisiteConceptIds: ['function'],
    aliases: ['argument', 'formal parameter'],
  },
  {
    id: 'return-value',
    title: 'Return Value',
    summary: 'The value a function produces back to its caller.',
    prerequisiteConceptIds: ['function'],
    aliases: ['result'],
  },
  {
    id: 'control-flow',
    title: 'Control Flow',
    summary: 'The order in which statements execute.',
    prerequisiteConceptIds: ['statement'],
    aliases: ['flow of control'],
  },
  {
    id: 'conditional',
    title: 'Conditional',
    summary: 'Executing code only when a condition is true.',
    prerequisiteConceptIds: ['control-flow', 'expression'],
    aliases: ['if statement', 'branching'],
  },
  {
    id: 'boolean-logic',
    title: 'Boolean Logic',
    summary: 'Combining true/false values with and, or, not.',
    prerequisiteConceptIds: ['expression'],
    aliases: ['logical operators'],
  },
  {
    id: 'short-circuit',
    title: 'Short-Circuit Evaluation',
    summary: 'When and/or stop early once the result is determined.',
    prerequisiteConceptIds: ['boolean-logic'],
    aliases: ['lazy evaluation', 'short-circuiting'],
  },
  {
    id: 'truthiness',
    title: 'Truthiness',
    summary: 'How non-boolean values are coerced to true/false in conditions.',
    prerequisiteConceptIds: ['boolean-logic'],
    aliases: ['falsy', 'truthy'],
  },
  {
    id: 'loop',
    title: 'Loop',
    summary: 'Repeating a block of code while a condition holds.',
    prerequisiteConceptIds: ['control-flow'],
    aliases: ['iteration', 'repetition'],
  },
  {
    id: 'for-loop',
    title: 'For Loop',
    summary: 'A loop with an explicit counter over a range or sequence.',
    prerequisiteConceptIds: ['loop'],
    aliases: ['counting loop'],
  },
  {
    id: 'while-loop',
    title: 'While Loop',
    summary: 'A loop repeating while a condition remains true.',
    prerequisiteConceptIds: ['loop'],
    aliases: ['condition loop'],
  },
  {
    id: 'collection',
    title: 'Collection',
    summary: 'A data structure holding multiple values.',
    prerequisiteConceptIds: ['variable', 'type'],
    aliases: ['container'],
  },
  {
    id: 'array',
    title: 'Array',
    summary: 'An indexed, fixed-size sequence of values.',
    prerequisiteConceptIds: ['collection'],
    aliases: ['list', 'vector'],
  },
  {
    id: 'string',
    title: 'String',
    summary: 'A sequence of characters representing text.',
    prerequisiteConceptIds: ['type'],
    aliases: ['text'],
  },
  {
    id: 'scope',
    title: 'Scope',
    summary: 'The region of code where a name is visible.',
    prerequisiteConceptIds: ['variable', 'function'],
    aliases: ['visibility', 'namespace'],
  },
  {
    id: 'recursion',
    title: 'Recursion',
    summary: 'A function calling itself on a smaller subproblem.',
    prerequisiteConceptIds: ['function', 'conditional'],
    aliases: ['self-reference'],
  },
  {
    id: 'base-case',
    title: 'Base Case',
    summary: 'The stopping condition that prevents infinite recursion.',
    prerequisiteConceptIds: ['recursion', 'conditional'],
    aliases: ['terminating case'],
  },
  {
    id: 'mutation',
    title: 'Mutation',
    summary: 'Changing a value or data structure in place.',
    prerequisiteConceptIds: ['assignment'],
    aliases: ['in-place change'],
  },
  {
    id: 'immutability',
    title: 'Immutability',
    summary: 'A value that cannot change after creation.',
    prerequisiteConceptIds: ['mutation'],
    aliases: ['constant data'],
  },
  {
    id: 'object',
    title: 'Object',
    summary: 'A bundle of state (fields) and behavior (methods).',
    prerequisiteConceptIds: ['variable', 'function'],
    aliases: ['instance'],
  },
  {
    id: 'class',
    title: 'Class',
    summary: 'A blueprint defining the fields and methods of objects.',
    prerequisiteConceptIds: ['object', 'type'],
    aliases: ['blueprint'],
  },
  {
    id: 'encapsulation',
    title: 'Encapsulation',
    summary: 'Hiding internal state behind an interface.',
    prerequisiteConceptIds: ['object', 'scope'],
    aliases: ['information hiding'],
  },
  {
    id: 'inheritance',
    title: 'Inheritance',
    summary: 'A class deriving fields and methods from another class.',
    prerequisiteConceptIds: ['class'],
    aliases: ['subclassing'],
  },
  {
    id: 'polymorphism',
    title: 'Polymorphism',
    summary: 'Treating different types through a common interface.',
    prerequisiteConceptIds: ['inheritance'],
    aliases: ['dynamic dispatch'],
  },
  {
    id: 'error-handling',
    title: 'Error Handling',
    summary: 'Detecting and responding to failures gracefully.',
    prerequisiteConceptIds: ['control-flow'],
    aliases: ['exceptions', 'try-catch'],
  },
  {
    id: 'memory-model',
    title: 'Memory Model',
    summary: 'How the language allocates and frees memory.',
    prerequisiteConceptIds: ['variable', 'mutation'],
    aliases: ['allocation'],
  },
  {
    id: 'ownership',
    title: 'Ownership',
    summary: 'A discipline where each value has a single owning scope.',
    prerequisiteConceptIds: ['memory-model', 'scope'],
    aliases: ['borrowing', 'lifetimes'],
  },
  {
    id: 'module-system',
    title: 'Module System',
    summary: 'Splitting code into reusable, importable units.',
    prerequisiteConceptIds: ['function', 'scope'],
    aliases: ['packages', 'imports'],
  },
  {
    id: 'testing',
    title: 'Testing',
    summary: 'Verifying code behaves correctly via executable checks.',
    prerequisiteConceptIds: ['function'],
    aliases: ['unit tests'],
  },
  {
    id: 'algorithm',
    title: 'Algorithm',
    summary: 'A precise, finite procedure for solving a problem.',
    prerequisiteConceptIds: ['function', 'control-flow'],
    aliases: ['procedure'],
  },
  {
    id: 'complexity',
    title: 'Computational Complexity',
    summary: 'How runtime/space grow with input size.',
    prerequisiteConceptIds: ['algorithm'],
    aliases: ['big-o', 'time complexity'],
  },
  {
    id: 'data-structure',
    title: 'Data Structure',
    summary: 'An organized way to store and access data.',
    prerequisiteConceptIds: ['collection'],
    aliases: ['container structure'],
  },
  {
    id: 'pointer',
    title: 'Pointer',
    summary: 'A value holding the address of other data.',
    prerequisiteConceptIds: ['memory-model'],
    aliases: ['reference'],
  },
  {
    id: 'map',
    title: 'Map',
    summary: 'A collection of key-to-value associations.',
    prerequisiteConceptIds: ['collection', 'array'],
    aliases: ['dictionary', 'dict', 'hashmap', 'hashtable', 'record'],
  },
  {
    id: 'set',
    title: 'Set',
    summary: 'A collection of unique values with no defined order.',
    prerequisiteConceptIds: ['collection'],
    aliases: ['unique collection'],
  },
  {
    id: 'iteration',
    title: 'Iteration',
    summary: 'Visiting each element of a collection in turn.',
    prerequisiteConceptIds: ['loop', 'collection'],
    aliases: ['traversal', 'enumeration'],
  },
  {
    id: 'index',
    title: 'Index',
    summary: 'A position used to access an element of an ordered collection.',
    prerequisiteConceptIds: ['array'],
    aliases: ['offset', 'position'],
  },
  {
    id: 'string-method',
    title: 'String Method',
    summary: 'An operation that transforms or inspects text.',
    prerequisiteConceptIds: ['string', 'function'],
    aliases: ['text operation'],
  },

  // ── Computing foundations ──────────────────────────────────────────
  {
    id: 'binary',
    title: 'Binary',
    summary: 'Base-2 representation of numbers using 0 and 1.',
    prerequisiteConceptIds: ['type'],
    aliases: ['base-2', 'bits'],
  },
  {
    id: 'cpu',
    title: 'CPU',
    summary: 'The processor that executes instructions one at a time.',
    prerequisiteConceptIds: ['program'],
    aliases: ['processor', 'central processing unit'],
  },
  {
    id: 'stack-memory',
    title: 'Stack',
    summary: 'LIFO region for function frames and local variables.',
    prerequisiteConceptIds: ['memory-model', 'function'],
    aliases: ['call stack region'],
  },
  {
    id: 'heap-memory',
    title: 'Heap',
    summary: 'Dynamic memory region for long-lived or large allocations.',
    prerequisiteConceptIds: ['memory-model'],
    aliases: ['dynamic memory'],
  },
  {
    id: 'compilation',
    title: 'Compilation',
    summary: 'Translating source code into machine code ahead of running.',
    prerequisiteConceptIds: ['program', 'cpu'],
    aliases: ['compiler'],
  },
  {
    id: 'interpretation',
    title: 'Interpretation',
    summary: 'Executing source code directly without a separate compile step.',
    prerequisiteConceptIds: ['program'],
    aliases: ['interpreter'],
  },
  {
    id: 'process',
    title: 'Process',
    summary: 'A running program with its own memory space.',
    prerequisiteConceptIds: ['program', 'memory-model'],
    aliases: ['running program'],
  },
  {
    id: 'filesystem',
    title: 'File System',
    summary: 'How an OS organizes data into files and directories.',
    prerequisiteConceptIds: ['program'],
    aliases: ['files', 'directories'],
  },
  {
    id: 'command-line',
    title: 'Command Line',
    summary: 'Text interface for invoking programs and managing files.',
    prerequisiteConceptIds: ['filesystem', 'process'],
    aliases: ['terminal', 'shell', 'cli'],
  },

  // ── Data structures (advanced) ─────────────────────────────────────
  {
    id: 'linked-list',
    title: 'Linked List',
    summary: 'A chain of nodes each pointing to the next.',
    prerequisiteConceptIds: ['data-structure', 'pointer'],
    aliases: ['singly linked list'],
  },
  {
    id: 'stack-ds',
    title: 'Stack (Data Structure)',
    summary: 'LIFO collection: push and pop from one end.',
    prerequisiteConceptIds: ['data-structure', 'collection'],
    aliases: ['lifo'],
  },
  {
    id: 'queue-ds',
    title: 'Queue (Data Structure)',
    summary: 'FIFO collection: enqueue at back, dequeue from front.',
    prerequisiteConceptIds: ['data-structure', 'collection'],
    aliases: ['fifo'],
  },
  {
    id: 'tree',
    title: 'Tree',
    summary: 'A hierarchical structure of nodes with one parent each.',
    prerequisiteConceptIds: ['data-structure', 'linked-list'],
    aliases: ['hierarchy'],
  },
  {
    id: 'binary-tree',
    title: 'Binary Tree',
    summary: 'A tree where each node has at most two children.',
    prerequisiteConceptIds: ['tree'],
    aliases: ['binary tree'],
  },
  {
    id: 'bst',
    title: 'Binary Search Tree',
    summary: 'An ordered binary tree enabling O(log n) search.',
    prerequisiteConceptIds: ['binary-tree', 'searching'],
    aliases: ['bst', 'ordered tree'],
  },
  {
    id: 'heap',
    title: 'Heap',
    summary: 'A tree satisfying the heap property; supports fast min/max.',
    prerequisiteConceptIds: ['binary-tree'],
    aliases: ['priority queue backing'],
  },
  {
    id: 'graph',
    title: 'Graph',
    summary: 'Nodes connected by edges; models networks and relations.',
    prerequisiteConceptIds: ['data-structure', 'tree'],
    aliases: ['network structure'],
  },
  {
    id: 'hashing',
    title: 'Hashing',
    summary: 'Mapping data to fixed-size values for fast lookup.',
    prerequisiteConceptIds: ['map', 'function'],
    aliases: ['hash function'],
  },
  {
    id: 'tuple',
    title: 'Tuple',
    summary: 'An ordered, fixed-size, immutable collection.',
    prerequisiteConceptIds: ['collection', 'immutability'],
    aliases: ['fixed record'],
  },

  // ── Algorithms ─────────────────────────────────────────────────────
  {
    id: 'searching',
    title: 'Searching',
    summary: 'Finding a target element within a collection.',
    prerequisiteConceptIds: ['algorithm', 'iteration'],
    aliases: ['lookup', 'find'],
  },
  {
    id: 'sorting',
    title: 'Sorting',
    summary: 'Arranging elements into a defined order.',
    prerequisiteConceptIds: ['algorithm', 'iteration', 'operator'],
    aliases: ['sort'],
  },
  {
    id: 'binary-search',
    title: 'Binary Search',
    summary: 'O(log n) search on a sorted collection by halving.',
    prerequisiteConceptIds: ['searching', 'sorting'],
    aliases: ['bisection search'],
  },
  {
    id: 'divide-and-conquer',
    title: 'Divide and Conquer',
    summary: 'Split a problem, solve parts, combine results.',
    prerequisiteConceptIds: ['recursion', 'algorithm'],
    aliases: ['split-solve-combine'],
  },
  {
    id: 'greedy',
    title: 'Greedy Algorithm',
    summary: 'Make the locally optimal choice at each step.',
    prerequisiteConceptIds: ['algorithm'],
    aliases: ['greedy'],
  },
  {
    id: 'dynamic-programming',
    title: 'Dynamic Programming',
    summary: 'Solve subproblems once and reuse their results.',
    prerequisiteConceptIds: ['recursion', 'algorithm', 'complexity'],
    aliases: ['dp', 'memoization'],
  },
  {
    id: 'backtracking',
    title: 'Backtracking',
    summary: 'Explore choices and undo them when they lead to a dead end.',
    prerequisiteConceptIds: ['recursion', 'algorithm'],
    aliases: ['constraint search'],
  },
  {
    id: 'bfs',
    title: 'Breadth-First Search',
    summary: 'Visit graph nodes level by level using a queue.',
    prerequisiteConceptIds: ['graph', 'queue-ds'],
    aliases: ['breadth first', 'level order'],
  },
  {
    id: 'dfs',
    title: 'Depth-First Search',
    summary: 'Visit graph nodes as deep as possible before backtracking.',
    prerequisiteConceptIds: ['graph', 'stack-ds', 'recursion'],
    aliases: ['depth first'],
  },

  // ── Software engineering ───────────────────────────────────────────
  {
    id: 'version-control',
    title: 'Version Control',
    summary: 'Tracking and managing changes to source code over time.',
    prerequisiteConceptIds: ['filesystem', 'program'],
    aliases: ['git', 'vcs'],
  },
  {
    id: 'branching',
    title: 'Branching',
    summary: 'Divergent lines of development in version control.',
    prerequisiteConceptIds: ['version-control'],
    aliases: ['branch', 'fork'],
  },
  {
    id: 'code-review',
    title: 'Code Review',
    summary: 'Systematically examining code before it is merged.',
    prerequisiteConceptIds: ['version-control'],
    aliases: ['peer review'],
  },
  {
    id: 'unit-testing',
    title: 'Unit Testing',
    summary: 'Testing individual units of code in isolation.',
    prerequisiteConceptIds: ['testing', 'function'],
    aliases: ['unit test'],
  },
  {
    id: 'integration-testing',
    title: 'Integration Testing',
    summary: 'Testing how multiple units work together.',
    prerequisiteConceptIds: ['unit-testing'],
    aliases: ['integration test'],
  },
  {
    id: 'debugging',
    title: 'Debugging',
    summary: 'Finding and fixing the root cause of incorrect behavior.',
    prerequisiteConceptIds: ['testing', 'error-handling'],
    aliases: ['troubleshooting'],
  },
  {
    id: 'design-pattern',
    title: 'Design Pattern',
    summary: 'A reusable solution to a recurring design problem.',
    prerequisiteConceptIds: ['object-oriented-design'],
    aliases: ['pattern'],
  },
  {
    id: 'object-oriented-design',
    title: 'Object-Oriented Design',
    summary: 'Modeling a system as cooperating objects.',
    prerequisiteConceptIds: ['object', 'function'],
    aliases: ['ood'],
  },
  {
    id: 'ci-cd',
    title: 'CI/CD',
    summary: 'Automating build, test, and deploy on every change.',
    prerequisiteConceptIds: ['version-control', 'unit-testing'],
    aliases: ['continuous integration', 'continuous deployment'],
  },

  // ── Web development ────────────────────────────────────────────────
  {
    id: 'http',
    title: 'HTTP',
    summary: 'The request/response protocol of the web.',
    prerequisiteConceptIds: ['process'],
    aliases: ['hypertext transfer protocol'],
  },
  {
    id: 'dom',
    title: 'DOM',
    summary: 'The in-memory tree a browser builds from HTML.',
    prerequisiteConceptIds: ['tree', 'html'],
    aliases: ['document object model'],
  },
  {
    id: 'html',
    title: 'HTML',
    summary: 'Markup that describes the structure of a web page.',
    prerequisiteConceptIds: ['program'],
    aliases: ['markup'],
  },
  {
    id: 'css',
    title: 'CSS',
    summary: 'Rules that describe how HTML elements are presented.',
    prerequisiteConceptIds: ['html'],
    aliases: ['styles'],
  },
  {
    id: 'rest',
    title: 'REST',
    summary: 'An architectural style for web APIs over HTTP.',
    prerequisiteConceptIds: ['http'],
    aliases: ['restful api'],
  },
  {
    id: 'json',
    title: 'JSON',
    summary: 'A text format for exchanging structured data.',
    prerequisiteConceptIds: ['object', 'string'],
    aliases: ['javascript object notation'],
  },
  {
    id: 'event-driven',
    title: 'Event-Driven Programming',
    summary: 'Flow controlled by events (clicks, messages, timers).',
    prerequisiteConceptIds: ['function', 'dom'],
    aliases: ['event handling'],
  },
  {
    id: 'async',
    title: 'Asynchronous Programming',
    summary: 'Starting work and handling results later without blocking.',
    prerequisiteConceptIds: ['function', 'event-driven'],
    aliases: ['async-await', 'promises', 'futures'],
  },
  {
    id: 'frontend-architecture',
    title: 'Frontend Architecture',
    summary: 'Organizing browser code into components and state.',
    prerequisiteConceptIds: ['dom', 'event-driven'],
    aliases: ['spa architecture'],
  },

  // ── Backend ────────────────────────────────────────────────────────
  {
    id: 'server',
    title: 'Server',
    summary: 'A process that listens for and handles requests.',
    prerequisiteConceptIds: ['http', 'process'],
    aliases: ['backend server'],
  },
  {
    id: 'api',
    title: 'API',
    summary: 'A defined interface for programs to talk to each other.',
    prerequisiteConceptIds: ['function', 'http'],
    aliases: ['application programming interface'],
  },
  {
    id: 'middleware',
    title: 'Middleware',
    summary: 'Functions chained between a request and its handler.',
    prerequisiteConceptIds: ['server', 'function'],
    aliases: ['request pipeline'],
  },
  {
    id: 'authentication',
    title: 'Authentication',
    summary: 'Verifying who a user is.',
    prerequisiteConceptIds: ['api', 'server'],
    aliases: ['auth'],
  },
  {
    id: 'authorization',
    title: 'Authorization',
    summary: 'Deciding what an authenticated user may do.',
    prerequisiteConceptIds: ['authentication'],
    aliases: ['permissions', 'authz'],
  },
  {
    id: 'caching',
    title: 'Caching',
    summary: 'Storing results to avoid recomputing or refetching them.',
    prerequisiteConceptIds: ['map', 'function'],
    aliases: ['cache'],
  },
  {
    id: 'rate-limiting',
    title: 'Rate Limiting',
    summary: 'Throttling how often a client may call an endpoint.',
    prerequisiteConceptIds: ['api'],
    aliases: ['throttling'],
  },

  // ── Databases ──────────────────────────────────────────────────────
  {
    id: 'database',
    title: 'Database',
    summary: 'An organized store of persistent data.',
    prerequisiteConceptIds: ['filesystem', 'data-structure'],
    aliases: ['db'],
  },
  {
    id: 'sql',
    title: 'SQL',
    summary: 'Declarative language for querying relational databases.',
    prerequisiteConceptIds: ['database', 'map'],
    aliases: ['structured query language'],
  },
  {
    id: 'index-db',
    title: 'Database Index',
    summary: 'A structure that speeds up lookups on a column.',
    prerequisiteConceptIds: ['database', 'hashing', 'tree'],
    aliases: ['index'],
  },
  {
    id: 'transaction',
    title: 'Transaction',
    summary: 'A unit of work that succeeds entirely or not at all.',
    prerequisiteConceptIds: ['database'],
    aliases: ['acid transaction'],
  },
  {
    id: 'normalization',
    title: 'Normalization',
    summary: 'Reducing redundancy by structuring tables with integrity.',
    prerequisiteConceptIds: ['database', 'sql'],
    aliases: ['normal forms'],
  },
  {
    id: 'nosql',
    title: 'NoSQL',
    summary: 'Non-relational database models (document, key-value, graph).',
    prerequisiteConceptIds: ['database'],
    aliases: ['document store', 'key-value store'],
  },

  // ── Systems programming ────────────────────────────────────────────
  {
    id: 'manual-memory',
    title: 'Manual Memory Management',
    summary: 'The programmer explicitly allocates and frees memory.',
    prerequisiteConceptIds: ['pointer', 'heap-memory'],
    aliases: ['malloc/free', 'manual allocation'],
  },
  {
    id: 'borrowing',
    title: 'Borrowing',
    summary: 'Temporarily lending access to a value without transferring ownership.',
    prerequisiteConceptIds: ['ownership'],
    aliases: ['rust borrowing', 'borrow checker'],
  },
  {
    id: 'lifetime',
    title: 'Lifetime',
    summary: 'The region of code in which a reference is valid.',
    prerequisiteConceptIds: ['borrowing', 'scope'],
    aliases: ['lifetimes', 'rust lifetime'],
  },
  {
    id: 'concurrency',
    title: 'Concurrency',
    summary: 'Making progress on multiple tasks within overlapping time.',
    prerequisiteConceptIds: ['process', 'function'],
    aliases: ['concurrent programming'],
  },
  {
    id: 'thread',
    title: 'Thread',
    summary: 'A unit of execution sharing memory within a process.',
    prerequisiteConceptIds: ['concurrency', 'process'],
    aliases: ['lightweight process'],
  },
  {
    id: 'synchronization',
    title: 'Synchronization',
    summary: 'Coordinating threads so they access shared data safely.',
    prerequisiteConceptIds: ['thread', 'concurrency'],
    aliases: ['locking', 'mutex'],
  },
  {
    id: 'networking',
    title: 'Networking',
    summary: 'How computers exchange data across connections.',
    prerequisiteConceptIds: ['process', 'http'],
    aliases: ['network protocols'],
  },

  // ── AI / ML ────────────────────────────────────────────────────────
  {
    id: 'statistics',
    title: 'Statistics',
    summary: 'Summarizing and reasoning about data with numbers.',
    prerequisiteConceptIds: ['function', 'collection'],
    aliases: ['descriptive statistics'],
  },
  {
    id: 'linear-algebra',
    title: 'Linear Algebra',
    summary: 'Vectors and matrices as the language of ML models.',
    prerequisiteConceptIds: ['function', 'array'],
    aliases: ['matrices', 'vectors'],
  },
  {
    id: 'machine-learning',
    title: 'Machine Learning',
    summary: 'Systems that improve at a task from data rather than rules.',
    prerequisiteConceptIds: ['statistics', 'linear-algebra', 'function'],
    aliases: ['ml'],
  },
  {
    id: 'neural-network',
    title: 'Neural Network',
    summary: 'Layered functions with learned weights mapping inputs to outputs.',
    prerequisiteConceptIds: ['machine-learning', 'linear-algebra'],
    aliases: ['neural net', 'nn'],
  },
  {
    id: 'training',
    title: 'Training',
    summary: 'Adjusting model parameters to reduce error on data.',
    prerequisiteConceptIds: ['neural-network', 'function'],
    aliases: ['model fitting', 'gradient descent'],
  },
  {
    id: 'transformer',
    title: 'Transformer',
    summary: 'Attention-based architecture behind modern language models.',
    prerequisiteConceptIds: ['neural-network'],
    aliases: ['attention model'],
  },
  {
    id: 'embedding',
    title: 'Embedding',
    summary: 'Representing items as vectors in a learned space.',
    prerequisiteConceptIds: ['machine-learning', 'linear-algebra'],
    aliases: ['vector representation'],
  },
  {
    id: 'llm',
    title: 'Large Language Model',
    summary: 'A transformer model trained on text at massive scale.',
    prerequisiteConceptIds: ['transformer', 'training'],
    aliases: ['large language model', 'foundation model'],
  },

  // ── Advanced development ───────────────────────────────────────────
  {
    id: 'parser',
    title: 'Parser',
    summary: 'Turns a sequence of tokens into a structured tree (AST).',
    prerequisiteConceptIds: ['tree', 'compilation'],
    aliases: ['parsing'],
  },
  {
    id: 'ast',
    title: 'AST',
    summary: 'A tree representing the structure of source code.',
    prerequisiteConceptIds: ['tree', 'parser'],
    aliases: ['abstract syntax tree'],
  },
  {
    id: 'static-analysis',
    title: 'Static Analysis',
    summary: 'Examining code without running it to find issues.',
    prerequisiteConceptIds: ['ast', 'parser'],
    aliases: ['linting'],
  },
  {
    id: 'cryptography',
    title: 'Cryptography',
    summary: 'Techniques for secure communication and data integrity.',
    prerequisiteConceptIds: ['function', 'binary'],
    aliases: ['crypto'],
  },
  {
    id: 'profiling',
    title: 'Profiling',
    summary: 'Measuring where a program spends time and memory.',
    prerequisiteConceptIds: ['debugging', 'complexity'],
    aliases: ['performance profiling'],
  },
  {
    id: 'distributed-systems',
    title: 'Distributed Systems',
    summary: 'Multiple computers cooperating as one system.',
    prerequisiteConceptIds: ['networking', 'concurrency'],
    aliases: ['distributed computing'],
  },
  {
    id: 'closure',
    title: 'Closure',
    summary: 'A function that captures variables from its defining scope.',
    prerequisiteConceptIds: ['scope', 'function'],
    aliases: ['lexical closure'],
  },
  {
    id: 'generator',
    title: 'Generator',
    summary: 'A function that yields values lazily, one at a time.',
    prerequisiteConceptIds: ['function', 'iteration'],
    aliases: ['lazy sequence', 'yield'],
  },
  {
    id: 'decorator',
    title: 'Decorator',
    summary: 'A function that wraps another to extend its behavior.',
    prerequisiteConceptIds: ['function', 'closure'],
    aliases: ['higher-order wrapper'],
  },
  {
    id: 'generic-type',
    title: 'Generics',
    summary: 'Writing code that works for many types via type parameters.',
    prerequisiteConceptIds: ['type', 'function'],
    aliases: ['parametric polymorphism', 'templates'],
  },
  {
    id: 'smart-contract',
    title: 'Smart Contract',
    summary: 'Self-executing code on a blockchain.',
    prerequisiteConceptIds: ['program', 'cryptography'],
    aliases: ['contract'],
  },
  {
    id: 'game-loop',
    title: 'Game Loop',
    summary: 'The update-render cycle driving real-time games.',
    prerequisiteConceptIds: ['loop', 'function'],
    aliases: ['render loop'],
  },
  {
    id: 'node',
    title: 'Node',
    summary: 'A container holding a value plus links to other nodes.',
    prerequisiteConceptIds: ['pointer', 'data-structure'],
    aliases: ['list node'],
  },
  {
    id: 'text',
    title: 'Text',
    summary: 'A sequence of characters representing human-readable content.',
    prerequisiteConceptIds: ['string'],
    aliases: ['plain text'],
  },
  {
    id: 'markup',
    title: 'Markup',
    summary: 'Text annotated with tags that label the structure and meaning of content.',
    prerequisiteConceptIds: ['text', 'type'],
    aliases: ['markup language'],
  },
  {
    id: 'element',
    title: 'Element',
    summary: 'A single tagged unit of a markup document (opening tag, content, closing tag).',
    prerequisiteConceptIds: ['markup'],
    aliases: ['tag', 'html element'],
  },
  {
    id: 'attribute',
    title: 'Attribute',
    summary: 'A key-value pair on a markup element providing extra information.',
    prerequisiteConceptIds: ['element'],
    aliases: ['html attribute'],
  },
  {
    id: 'query',
    title: 'Query',
    summary: 'A request to retrieve or modify data from a data store.',
    prerequisiteConceptIds: ['data-structure'],
    aliases: ['database query'],
  },
  {
    id: 'table',
    title: 'Table',
    summary: 'A collection of rows and columns storing records in a relational database.',
    prerequisiteConceptIds: ['data-structure'],
    aliases: ['database table', 'relation'],
  },
  {
    id: 'relational-model',
    title: 'Relational Model',
    summary: 'Organizing data as related tables with keys connecting them.',
    prerequisiteConceptIds: ['table', 'foreign-key'],
    aliases: ['relational database model'],
  },
  {
    id: 'foreign-key',
    title: 'Foreign Key',
    summary: 'A column referencing the primary key of another table to express a relationship.',
    prerequisiteConceptIds: ['table'],
    aliases: ['fk'],
  },
  {
    id: 'commit',
    title: 'Commit',
    summary: 'A recorded snapshot of the project state at one point in time in version control.',
    prerequisiteConceptIds: ['version-control'],
    aliases: ['git commit', 'revision'],
  },
  {
    id: 'branch',
    title: 'Branch',
    summary: 'A movable label pointing at a commit, enabling isolated lines of work.',
    prerequisiteConceptIds: ['commit', 'version-control'],
    aliases: ['git branch'],
  },
  {
    id: 'working-directory',
    title: 'Working Directory',
    summary: 'The files on disk that you edit, separate from staged and committed state.',
    prerequisiteConceptIds: ['version-control'],
    aliases: ['working tree'],
  },
  {
    id: 'model',
    title: 'Model',
    summary: 'A learned function that maps inputs to predicted outputs in machine learning.',
    prerequisiteConceptIds: ['machine-learning', 'function'],
    aliases: ['ml model', 'trained model'],
  },
  {
    id: 'feature',
    title: 'Feature',
    summary: 'A measurable property of data used as input to a machine learning model.',
    prerequisiteConceptIds: ['machine-learning'],
    aliases: ['input feature'],
  },
  {
    id: 'supervised-learning',
    title: 'Supervised Learning',
    summary: 'Training a model on labeled examples to predict outputs for new inputs.',
    prerequisiteConceptIds: ['machine-learning', 'training'],
    aliases: ['supervised machine learning'],
  },
]

export const CONCEPT_BY_ID: Record<string, Concept> = Object.fromEntries(
  CONCEPTS.map((concept) => [concept.id, concept]),
)

export function getConcept(id: string): Concept | undefined {
  return CONCEPT_BY_ID[id]
}

export function listConcepts(): Concept[] {
  return CONCEPTS
}
